### PR TITLE
Setting tree root for new tree as well

### LINKED ISSUE #1612: discover -f does not work correctly since version 1.18
Second run of `tmt run --id X discover -f` does not discover any test.
Try this in some test directory, e.g. in [1].

```
$ rpm -q tmt
tmt-1.17.0-1.fc35.noarch
$ rm -rf /var/tmp/tmt/*
$ tmt run --id X plans --default tests --name . discover -fv
/var/tmp/tmt/X

/plans/default
    discover
        how: fmf
        directory: /home/dapospis/test/git/SP_components/tests
        hash: dba9cae
        summary: 1 test selected
            /usbguard/Sanity/selinux
[0 dapospis@sopos tests(master).+ selinux]$ tmt run --id X plans --default tests --name . discover -fv
/var/tmp/tmt/X

/plans/default
    discover
        how: fmf
        directory: /home/dapospis/test/git/SP_components/tests
        hash: dba9cae
        summary: 1 test selected
            /usbguard/Sanity/selinux
```
```
$ rpm -q tmt
tmt-1.18.0-1.20221019090005434264.main.17.g5208e63.fc35.noarch
$ rm -rf /var/tmp/tmt/*
$ tmt run --id X plans --default tests --name . discover -fv
/var/tmp/tmt/X

/plans/default
    discover
        how: fmf
        directory: /home/dapospis/test/git/SP_components/tests
        hash: dba9cae
        summary: 1 test selected
            /usbguard/Sanity/selinux
$ tmt run --id X plans --default tests --name . discover -fv
/var/tmp/tmt/X

/plans/default
    discover
        how: shell
        summary: 0 tests selected
        warning: No tests found, finishing plan.

```
1. https://github.com/RedHat-SP-Security/tests/tree/master/usbguard/Sanity/selinux

### PR DESCRIPTION
**Pull request by adiosnb**
Closes #1612

### CODE REVIEW

**Comment by lukaszachy** [comment]
LGTM however we should add test - how about https://github.com/teemtee/tmt/compare/atomasov-fix-1612...lukaszachy:tmt:atomasov-fix-1612 ?

**Comment by psss** [comment]
Thanks for the fix, looks good, and thanks @lukaszachy for the test!

Just to clarify what caused the problem: When the tree `root` was not set for the whole tree, the metadata root would not be correctly stored into `run.yaml` during `Run.save()`:

```yaml
root:
plans:
  - /plans/default
steps:
  - discover
environment: {}
remove: false
__class__:
    module: tmt.base
    name: RunData
```

**Comment by adiosnb** [comment]
> LGTM however we should add test - how about [atomasov-fix-1612...lukaszachy:tmt:atomasov-fix-1612](https://github.com/teemtee/tmt/compare/atomasov-fix-1612...lukaszachy:tmt:atomasov-fix-1612) ?

Looks good. Tried and merged.

**Review by psss — APPROVED** [review]
Looks good, thanks much to both! @lukaszachy, if you don't mind, I suggest to simplify the test in eaa15cdb, I believe the straightforward readability outweighs the duplicated line.

**Pull request merged**
