### PR TITLE
Artemis API version may contain multiple integers

### PR DESCRIPTION
**Pull request by tinez**
The current one i.e. is 0.0.48.

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Comment by happz** [comment]
Wow, the patch is trivial, but I certainly did not want to skip tests :O I did set auto-merge, but I also asked Packit to run checks, the merge happened way too early :/

**Comment by psss** [comment]
This might be related to the fact the @tinez cannot run tests (the pull request is from a fork). @lachmanfrantisek, should Packit report a different status for such jobs to prevent automerging without any test results?

**Comment by happz** [comment]
Aaaah, and pre-commit succeeded and that was enough for Github to proceed...

**Comment by psss** [comment]
But there are (or at least should be) six other required status checks which have to pass before merging. What is weird, I don't see them in some pull requests...

**Comment by mfocko** [comment]
There are reports of issues with that when having the merge queue enabled, not sure if it's related to it even when you don't have it set... We couldn't merge anything though :D

**Comment by psss** [comment]
Yes, the merge queue is not enabled so I guess it should not be related to this new feature.

**Pull request merged**
