### PR TITLE
Add link config validation

### LINKED ISSUE #84: Implement a user configuration
Seems we'll soon need a way how to store user configuration data. For example `tmt test export --nitrate` might need a `url` to the test case management system.

Brainstorming first ideas here: What about storing data under `$HOME/.config/tmt` in the form of an `fmf` tree? For the above-mentioned example we could have something like this:

    /test/convert/nitrate:
        url: https://nitrate.example.com/

This would work naturaly / consistently with how the rest of data is handled in `tmt`.

### PR DESCRIPTION
**Pull request by therazix**
This PR extracts the `Config` class from `tmt.utils` into its own file and also introduces config validation using Pydantic models. Currently, validation is applied only to the link configuration.

Resolves #84.

Pull Request Checklist

* [x] implement the feature
* [x] extend the test coverage

### CODE REVIEW

**Comment by martinhoyer** [comment]
Nice!
The '<2' limit for pydantic version won't work as Fedora only have v2.  
Do you know why epel9 was never updated to v2?  

What do you think about this settings for BaseModel?
https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_runtime-evaluated-base-classes

**Comment by therazix** [comment]
I updated Pydantic to v2, but I'm not sure how to make it work on EPEL 9, which only supports v1.

> What do you think about this settings for BaseModel?
> https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_runtime-evaluated-base-classes

It may be a good idea to add that. I didn't encounter any problems without it, but it may be needed in some scenarios. Added in c49656d1e83ccf152a4ffbdd10b0b9fef19b28d1

**Review by martinhoyer — APPROVED** [review]

**Review by skycastlelily — APPROVED** [review]
LGTM:)

**Comment by skycastlelily** [comment]
I followed the extended test ,and put the following ~/.config/link.fmf:

```
issue-tracker:
  - type: jira
    url: https://issues.redhat.com
    tmt-web-url: http://tmt.testing-farm.io/
    unkown: value
```
Then run tmt link command, got no warning, I guess we could warn users by printing the str(error.__cause__),
similar as how your test works? @therazix

**Comment by therazix** [comment]
> I followed the extended test ,and put the following ~/.config/link.fmf:
> 
> ```
> issue-tracker:
>   - type: jira
>     url: https://issues.redhat.com
>     tmt-web-url: http://tmt.testing-farm.io/
>     unkown: value
> ```
> 
> Then run tmt link command, got no warning, I guess we could warn users by printing the str(error.**cause**), similar as how your test works? @therazix

You are right, thanks for the review. The issue was that `SpecificationError` was caught by `except tmt.utils.MetadataError`, so no exception was raised. It should be fixed in 0b7cd2be01151429bdc6af1798f4262516c19565.

**Comment by skycastlelily** [comment]
> It should be fixed in 0b7cd2b.

Confirmed.

**Review by seberm — APPROVED** [review]

**Review by psss — APPROVED** [review]
Very nice! The error messages which `pydantic` generates for invalid data look very useful. Thanks for implementing this!

**Comment by psss** [comment]
Rawhide failure irrelevant, merging.

**Pull request merged**
