### PR TITLE
Release tmt-1.21.0

### PR DESCRIPTION
**Pull request by lukaszachy**
Follow the steps below to create a new major or minor release:

- [x] Run the full test coverage using ``tmt -c how=full run``
- [x] Use ``git log --oneline --no-decorate x.y-1..`` to generate the changelog
- [x] Update ``README`` with new contributors since the last release
- [x] Add a ``Release tmt-x.y.0`` commit with the specfile update
- [x] Create a pull request with the commit, ensure tests pass

Release a new package to Fedora and EPEL repositories:

- [x] Move the ``fedora`` branch to point to the new release
- [x] Create a source rpm using the ``make srpm`` command
- [x] Enable Fedora kerberos ``kinit nick@FEDORAPROJECT.ORG``
- [x] Change to the fedora rpms git or ``fedpkg clone tmt``
- [x] Check out the rawhide branch ``git checkout rawhide``
- [x] Import the srpm using ``fedpkg import /path/to/the/srpm``
- [x] Restore any files removed by fedpkg if necessary
- [x] Ensure the proposed changes are ok and commit them
- [x] Create a pull request against rawhide from your fork
- [x] After tests pass, merge the pull request to rawhide
- [x] Build the package for rawhide ``fedpkg build --nowait``
- [x] Build package for all `active releases`__   ``git checkout f33 && git merge rawhide && git push && fedpkg build --nowait``
- [x] Create a bodhi update for each release   ``git checkout f33 && fedpkg update --type enhancement --notes 'Update title'``

Finally, if everything went well:

- [x] Tag the commit with ``x.y.0``, push tags ``git push --tags``
- [ ] **Manually*- [ ] merge the original release pull request on github (to avoid rebase)   ``git checkout main && git merge --ff-only <release_branch> && git push origin main``
- [ ] Create a new `github release`__ based on the tag above
- [ ] If the automation triggered by publishing the new github release   was not successful, publish the fresh code to the `pypi`__   repository manually using ``make wheel && make upload``
- [ ] Once the `copr build`__ is completed, move the ``quay`` branch to   point to the release commit as well to build fresh container   images.
- [ ] Close the corresponding release milestone

### CODE REVIEW

**Review by psss — APPROVED** [review]

**Comment by lukaszachy** [comment]
Failures for tests/full: Beaker - 4 hours was not enough to finish
Local laptop:
#### /tests/discover/libraries
Assert of debug message from stdout instead of stderr. Will be fixed post release (use rlRun -s instead of tee)

#### /tests/execute/reboot/reuse_provision
Looks like a real problem. Reboot doesn't happen - #1829

#### /tests/provision/virtual/dependencies

**Comment by lukaszachy** [comment]
Note to self: We really have to run test/full at least weekly. These last minute surprises are nasty.

**Comment by lukaszachy** [comment]
Back to square one. I'll continue tomorrow.

**Comment by lukaszachy** [comment]
The only failure now is /tests/provision/virtual/dependencies (VM in VM is too slow Failed to connect in 60s.) --> PASS

**Comment by psss** [comment]
Thanks for taking care of the release, @lukaszachy. And for resolving all the issues.

> We really have to run test/full at least weekly. These last minute surprises are nasty.

Good point. We could possibly enable some of the tests for pull requests as well.

**Pull request merged**
