### PR TITLE
Group discover/fmf options, improve wording a bit

### PR DESCRIPTION
**Pull request by psss**
Define related options closer together.
Use a better wording for some of the options.

### CODE REVIEW

**Comment by psss** [comment]
When reading #2174 I've noticed several unclear option descriptions. The new descriptions should be hopefully a bit more clear. I've also grouped all relevant options together. However we still get two `--dist-git` options at the very beginning of the help:

```
  -h, --how METHOD                Use specified method to discover tests.
  --dist-git-source               Extract DistGit sources.
  --dist-git-type fedora|centos|redhatgitlab|rhel
                                  Use the provided DistGit handler instead of
                                  the auto detection.
  -u, --url REPOSITORY            URL of the git repository with fmf metadata.
  -r, --ref REVISION              Branch, tag or commit specifying the git
                                  revision.
  -p, --path ROOT                 Path to the metadata tree root.
  -t, --test NAMES                Select tests by name.
```

This is because they are inherited from the `DiscoverStepData` class and thus created first. @happz, any idea how we could nicely group these with the other `--dist-git` options? Define something like order for the fields?

**Review by lukaszachy — APPROVED** [review]

**Comment by happz** [comment]
> When reading #2174 I've noticed several unclear option descriptions. The new descriptions should be hopefully a bit more clear. I've also grouped all relevant options together. However we still get two `--dist-git` options at the very beginning of the help:
> 
> ```
>   -h, --how METHOD                Use specified method to discover tests.
>   --dist-git-source               Extract DistGit sources.
>   --dist-git-type fedora|centos|redhatgitlab|rhel
>                                   Use the provided DistGit handler instead of
>                                   the auto detection.
>   -u, --url REPOSITORY            URL of the git repository with fmf metadata.
>   -r, --ref REVISION              Branch, tag or commit specifying the git
>                                   revision.
>   -p, --path ROOT                 Path to the metadata tree root.
>   -t, --test NAMES                Select tests by name.
> ```
> 
> This is because they are inherited from the `DiscoverStepData` class and thus created first. @happz, any idea how we could nicely group these with the other `--dist-git` options? Define something like order for the fields?

Correct, that's because of the order of fields in data classes. I bet we could do something about it via `field()`, maybe some `in_help_order` parameter, or `in_help_after='--the-first-dist-git-option'`, plus overriding how Click renders help for options:

```python
    def format_options(self, ctx: Context, formatter: HelpFormatter) -> None:
        """Writes all the options into the formatter if they exist."""
        opts = []
        for param in self.get_params(ctx):
            rv = param.get_help_record(ctx)
            if rv is not None:
                opts.append(rv)

        if opts:
            with formatter.section(_("Options")):
                formatter.write_dl(opts)
```

Instead of basic `get_params()`, we could employ something smarter. No idea how to attach metadata like our ordering to options, but Click has been sane so far, I'd say there would be a way. Probably not a one-liner though, I wouldn't block this patch on this solution...

**Review by thrix — APPROVED** [review]
LGTM

**Review by janhavlin — APPROVED** [review]

**Comment by psss** [comment]
> Or maybe adding option groups? `field(..., help_group='dist-git')` and somehow create those groups as needed, dynamically?

A help group sounds like a nice idea! Filed as #2215.

**Pull request merged**
