### PR TITLE
Add a `Toolbelt Catalog` entry for `tmt`

### PR DESCRIPTION
**Pull request by psss**
To be used to build the `Toolbelt Catalog`.
Fix https://issues.redhat.com/browse/QC-66

Pull Request Checklist

* [x] write the documentation

### CODE REVIEW

**Comment by happz** [comment]
@psss is the file name mandatory? I'm wondering whether it'd make sense to leave the door open to all those other catalogs by making this one less generic, e.g. by calling it `toolbelt-catalog.info`.

**Comment by psss** [comment]
> @psss is the file name mandatory?

Yes, the system does not accept anything else. I was a bit afraid that it will have to be in the root directory, but fortunately it can be in a different directory. But that's it about what we can do here.

**Review by happz — APPROVED** [review]
Thou shalt have no other catalogs before me...

**Comment by psss** [comment]
Oh! And I'm taking back, what I just said. I would swear I tried it yesterday with a different name and it would not accept anything else, but today it does :-) I'll use `toolbelt-catalog.yaml` then.

**Comment by psss** [comment]
The sister pull request for `fmf` is ready for review as well:

* teemtee/fmf/pull/216

**Pull request merged**
