### PR TITLE
Run tests with `interactive` mode during `tmt try`

### PR DESCRIPTION
**Pull request by psss**
This is needed if for example a `bash` line is included in the test script so that user can investigate in the middle of a test.

Pull Request Checklist

* [x] implement the feature
* [x] extend the test coverage

### CODE REVIEW

**Comment by psss** [comment]
This will need some more work as currently the `interactive` mode causes the exit code to be ignored: Here's summary from @happz:

> Command.run() should catch the errors, turn them into RunError, and let the caller deal with them. login can ignore them, execute probably shouldn't. feels like a bit more work for one quick and short patch though :confused:

Moving to `1.31`.

**Comment by happz** [comment]
Related refactoring of interactive commands: https://github.com/teemtee/tmt/pull/2554

**Comment by psss** [comment]
@happz, @thrix, I had to adjust exit code handling in the wrapper in 07b654b8. That `$!` was a typo, right? After the change interactive mode seems to be working fine and shell test results are correctly reported. I just see the following error when entering the interactive session:

```
bash: cannot set terminal process group (1076789): Inappropriate ioctl for device
bash: no job control in this shell
```

Any idea how to get rid of those?

**Comment by happz** [comment]
> @happz, @thrix, I had to adjust exit code handling in the wrapper in [07b654b](https://github.com/teemtee/tmt/commit/07b654b8106d2cc82b3ff2684bb4614373cdb822). That `$!` was a typo, right? After the change interactive mode seems to be working fine and shell test results are correctly reported.

Definitely a typo.

> I just see the following errors when entering the interactive session:
> 
> ```
> bash: cannot set terminal process group (1076789): Inappropriate ioctl for device
> bash: no job control in this shell
> ```
> 
> Any idea how to get rid of those?

Hm, is there a reproducer? Might be some combination of provision plugin & tty, like the test not having a control terminal yet being asked to mess with tty or something. But I have no suspicion, it's something I would have to debug and look for explanations in docs.

**Comment by psss** [comment]
> Hm, is there a reproducer? Might be some combination of provision plugin & tty, like the test not having a control terminal yet being asked to mess with tty or something. But I have no suspicion, it's something I would have to debug and look for explanations in docs.

Happens only for `local` provision, reproducer is simple:

```yaml
/plan:
    provision:
        how: local
    discover:
        how: fmf
    execute:
        how: tmt

/test:
    test: bash
```

And run with interactive mode:

```
tmt try -p plan
```

With `container` or `virtual` there's no error.

**Comment by happz** [comment]
> > Hm, is there a reproducer? Might be some combination of provision plugin & tty, like the test not having a control terminal yet being asked to mess with tty or something. But I have no suspicion, it's something I would have to debug and look for explanations in docs.
> 
> Happens only for `local` provision, reproducer is simple:
> 
> ```yaml
> /plan:
>     provision:
>         how: local
>     discover:
>         how: fmf
>     execute:
>         how: tmt
> 
> /test:
>     test: bash
> ```
> 
> And run with interactive mode:
> 
> ```
> tmt try -p plan
> ```
> 
> With `container` or `virtual` there's no error.

No idea how to resolve it, now. It seems to be fairly harmless, at least after a few runs. If I drop `start_new_session=True` from the `is interactive` branch in `Command.run()`, messages go away. But I would sort of expect it to be the other way around, i.e. shell that's not a session leader would not have job control, but this suggests it's the one started with `start_new_session=True`. I suppose it's somehow related to what SSH does for us thanks to `-tt`, and why we don't have tty support in the `local` plugin. I'd suggest looking into enabling tty support in `local`, the issue you're observing here might very well get resolved as well. But I don't have any immediate idea :/

**Comment by psss** [comment]
> If I drop `start_new_session=True` from the `is interactive` branch in `Command.run()`, messages go away.

Actually, that would be aligned with what was used before the changes in #2554:

https://github.com/teemtee/tmt/blob/009fc0bbd0ddcf613e65b7f435f6468c3cd877d2/tmt/utils.py#L681-L690

So, I guess, it makes sense to keep that part as it was before.

**Comment by happz** [comment]
> > If I drop `start_new_session=True` from the `is interactive` branch in `Command.run()`, messages go away.
> 
> Actually, that would be aligned with what was used before the changes in #2554:
> 
> https://github.com/teemtee/tmt/blob/009fc0bbd0ddcf613e65b7f435f6468c3cd877d2/tmt/utils.py#L681-L690
> 
> So, I guess, it makes sense to keep that part as it was before.

Maybe. It's highly unsatisfactory, I mean the lack of explanation and motivation because I don't understand why there are complaints with `local` and not with `virtual`, for example. Feel free to comment it out, although it'd be nice to have a comment there on why it's commented out and therefore not doing the same thing as the non-interactive spawn. The warning will go away, and I will remain unhappy...

**Comment by psss** [comment]
Ok, added a comment and covered by a test in 184e3b6c.

**Review by happz — APPROVED** [review]

**Pull request merged**
