### PR TITLE
Move abort detection into test invocation

### PR DESCRIPTION
**Pull request by happz**
Similar to reboot detection, hiding the details from individual execution plugins.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by therazix — COMMENTED** [review]
LGTM. Just one question. Shouldn't the `check_abort_file` method be removed from the `ExecutePlugin` class as it is no longer used?

**Comment by happz** [comment]
@therazix absolutely, removed in e0d050cb

**Review by therazix — APPROVED** [review]

**Comment by happz** [comment]
> Nice, I just wonder how it worked before, when there was:
> 
> ```
> if (abort or self.data.exit_first and
>     result.result not in (ResultOutcome.PASS, ResultOutcome.INFO)):
> ```
> 
> and now we're iterating `for result in invocation.results`. Was that a bug?

I believe it was a bug, because it was checking `result.result`, and `result` was whatever the loop saw as the last item, most likely `invocation.results[-1]`:

```python
                if abort:
                    for result in invocation.results:
                        # In case of aborted all results in list will be aborted
                        result.note = 'aborted'

...

                for result in invocation.results:
                    logger.verbose(
                        f"{_format_duration(result)} {result.show()} [{progress}]",
                        shift=shift)

...

                if (abort or self.data.exit_first and
                        result.result not in (ResultOutcome.PASS, ResultOutcome.INFO)):
```

So only the last result was considered, which does not seem right.

**Pull request merged**
