### PR TITLE
Fix /plans/provision/virtual to set correct PROVISION_* variable

### PR DESCRIPTION
**Pull request by happz**
Plus there was one lone test using the wrong one. Fixing both.

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]

**Review by psss — APPROVED** [review]
Oh, that was an unpleasant leftover. And I would swear I grepped through all the files. Apparently not. Thanks for catching this!

**Comment by happz** [comment]
> Two failures:
> 
> * `/tests/provision/user` doesn't work with --user (machine boots but account seems to be locked)
> * `/tests/prepare/multihost` fails to connect, maybe fixed by [Disable password authentication when using keys #2695](https://github.com/teemtee/tmt/pull/2695) ?

Indeed fits the description :/

Anyway: lovely, way fewer failures than I expected, and definitely way fewer than what I saw in my local run. Some of those will be local setup, but I did find some genuine tracebacks, for example.

**Comment by happz** [comment]
> > Two failures:
> > 
> > * `/tests/provision/user` doesn't work with --user (machine boots but account seems to be locked)
> > * `/tests/prepare/multihost` fails to connect, maybe fixed by [Disable password authentication when using keys #2695](https://github.com/teemtee/tmt/pull/2695) ?
> 
> Indeed fits the description :/
> 
> Anyway: lovely, way fewer failures than I expected, and definitely way fewer than what I saw in my local run. Some of those will be local setup, but I did find some genuine tracebacks, for example:

* https://github.com/teemtee/tmt/issues/2723

**Comment by happz** [comment]
And since the issues are known or tracked, I believe we can merge this PR :)

**Comment by happz** [comment]
Added a fix for `/tests/provision/user`

**Pull request merged**
