### PR TITLE
Improve type-hints

### PR DESCRIPTION
**Pull request by LecrisUT**
- [ ] Use `__future__.annotations`. This allows to use `3.11` syntax and typing checks while maintaining compatibility with older python versions.
- [x] Bump mypy python_version to 3.11
- [ ] Switch `cast` to a different approach. Not sure what/how to do for this one

### CODE REVIEW

**Comment by thrix** [comment]
Is it expected `Optional` is going away in the future Python releases, I, personally, prefer it in the code :(

**Comment by LecrisUT** [comment]
> Is it expected `Optional` is going away in the future Python releases, I, personally, prefer it in the code :(

I don't see any official plans for removal and it is not officially deprecated: https://docs.python.org/3/library/typing.html#typing.Optional, unlike `typing.Dict`, etc. I guess the syntax can be retained. But `Union` should definitely be removed.

What is everyone else's opinion on this?

**Comment by happz** [comment]
> > Is it expected `Optional` is going away in the future Python releases, I, personally, prefer it in the code :(
> 
> I don't see any official plans for removal and it is not officially deprecated: https://docs.python.org/3/library/typing.html#typing.Optional, unlike `typing.Dict`, etc. I guess the syntax can be retained. But `Union` should definitely be removed.
> 
> What is everyone else's opinion on this?

+1 for keeping `Optional`, for me it makes the optionality of a value more visible than `| None`. The "optional" label is easier to note for me.

+1 for getting rid of `Union`, with my C origins I for one read `foo | bar` better than `Union[foo, bar]`. But I wouldn't mind if it stays either.

**Comment by thrix** [comment]
+1 for moving Union also from me

**Comment by LecrisUT** [comment]
Ok, I will drop the change of `Optional` in this MR and only do:
- Add `__future__.annotations`
- Bump `mypy` python version
- Remove the forward declared string annotations
- Remove `Union`
- Move `TypeAlias` and `TypeVar` to if `TYPE_CHECKING` guard. This one would further be improved by python 3.12 syntax, but unfortunately there is no backwards compatibility for that. Hopefully some magic package can come up to help with that as well

**Pull request closed without merging**
