### PR TITLE
Improve logging by `tmt.utils.wait()`

### PR DESCRIPTION
**Pull request by happz**
And fixes one particular message that was using pre-check timestamp in its message, which, when the check callback takes anything but a jiffie, can result in a very puzzling message.

### CODE REVIEW

**Comment by happz** [comment]
@psss I added this one to 1.21 right away, it's a trivial logging improvement - it should be fairly cheap to review & merge.

**Review by lukaszachy — APPROVED** [review]
Nice. Thanks.

**Review by psss — APPROVED** [review]

**Pull request merged**
