### PR TITLE
Use separate examples in the test specification

### LINKED ISSUE #738: Documentation: ambiguous paragraph in Specification / Tests / test
Both the wording and examples in [Specification / Tests / test](https://tmt.readthedocs.io/en/latest/spec/tests.html#test) create an impression that it is possible to run more tests with `test` key in one test file. But an attempt to do so results in *duplicate keys* error.
The possible way to execute more tests (or eg. parametrized test script) in a single file would be to nest the levels like this:
```
/foo:
    test: ./test.sh foo
/bar:
    test: ./test.sh bar
```
This could be changed in documentation to avoid ambiguity.

### PR DESCRIPTION
**Pull request by psss**
Use a list of examples and add a comment to each to prevent
confusion that the same key can be used multiple times in a single
config. Remove `relevancy` which has been obsoleted long time ago.

Resolves #738.

### CODE REVIEW

**Review by dkarpele — APPROVED** [review]

**Comment by lukaszachy** [comment]
I still think we should produce multiple Literal blocks - proposed spec change in #1126

**Comment by psss** [comment]
> I still think we should produce multiple Literal blocks - proposed spec change in #1126

Yeah, you're right. I've rebased on the freshly merged support for multiple examples and updated all examples in the test spec. @lukaszachy, @befeleme, please have a look.

**Comment by lukaszachy** [comment]
Screenshot 2022-04-01 at 09-38-05 Tests — tmt documentation

IMO looks great.

**Review by lukaszachy — APPROVED** [review]

**Comment by befeleme** [comment]
I second @lukaszachy, the examples look clear and lose the ambiguity from the previous versions.

**Comment by psss** [comment]
Great, thanks for the feedback!

**Pull request merged**
