### PR TITLE
Check packages are installed via debuginfo-install

### PR DESCRIPTION
**Pull request by idorax**
Fixes: #1780

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Review by psss — CHANGES_REQUESTED** [review]
Thanks for looking into this. Looks reasonable but some tests are failing:

 * `/tests/prepare/{install,recommend}` seem to be related to the change
 * `/tests/execute/upgrade/override` should be fixed by rebasing on the latest `main`

Please, have a look. Would be nice to adjust tests to cover both successful and unsuccessful debuginfo package installation.

**Comment by idorax** [comment]
> ... Would be nice to adjust tests to cover both successful and unsuccessful debuginfo package installation.

From [the test log][01],
```bash
Run command: podman exec tmt-003-ulUhQCwS /bin/bash -c 'export TMT_PLAN_DATA=/var/tmp/tmt/run-003/debuginfo/centos-8/data; export TMT_TREE=/var/tmp/tmt/run-003/debuginfo/centos-8/tree; debuginfo-install -y grep elfutils-debuginfod'
            cmd: debuginfo-install -y grep elfutils-debuginfod
            out: Last metadata expiration check: 0:00:41 ago on Thu Jan 19 12:38:41 2023.
...<snip>...
            out: Install  5 Packages
            out: 
            out: Total download size: 3.5 M
            out: Installed size: 18 M
            out: Downloading Packages:
            out: (1/5): elfutils-debuginfod-debuginfo-0.188-3.el  18 MB/s | 812 kB     00:00    
            out: (2/5): grep-debuginfo-3.1-6.el8.x86_64.rpm       41 MB/s | 246 kB     00:00    
            out: (3/5): elfutils-debugsource-0.188-3.el8.x86_64.  13 MB/s | 781 kB     00:00    
            out: (4/5): grep-debugsource-3.1-6.el8.x86_64.rpm     22 MB/s | 271 kB     00:00    
            out: (5/5): elfutils-debuginfo-0.188-3.el8.x86_64.rp  19 MB/s | 1.4 MB     00:00    
            out: --------------------------------------------------------------------------------
            out: Total                                            46 MB/s | 3.5 MB     00:00     
            out: Running transaction check
            out: Transaction check succeeded.
            out: Running transaction test
            out: Transaction test succeeded.
            out: Running transaction
            out:   Preparing        :                                                        1/1 
            out:   Installing       : elfutils-debugsource-0.188-3.el8.x86_64                1/5 
...<snip>...
            out: 
            out: Installed:
            out:   elfutils-debuginfo-0.188-3.el8.x86_64                                         
            out:   elfutils-debuginfod-debuginfo-0.188-3.el8.x86_64                              
            out:   elfutils-debugsource-0.188-3.el8.x86_64                                       
            out:   grep-debuginfo-3.1-6.el8.x86_64                                               
            out:   grep-debugsource-3.1-6.el8.x86_64                                             
            out: 
            out: Complete!
        Run command: podman exec tmt-003-ulUhQCwS /bin/bash -c 'export TMT_PLAN_DATA=/var/tmp/tmt/run-003/debuginfo/centos-8/data; export TMT_TREE=/var/tmp/tmt/run-003/debuginfo/centos-8/tree; rpm -q grep elfutils-debuginfod'
            cmd: rpm -q grep elfutils-debuginfod
            out: grep-3.1-6.el8.x86_64
            out: package elfutils-debuginfod is not installed
        Command returned '1'.
```

[01]: https://artifacts.dev.testing-farm.io/d83fc3c0-89ac-4b8b-92fd-f2f789795fa7/work-advanced2u0ep72g/plans/features/advanced/execute/data/tests/prepare/install/output.txt

The cmd to install packages is `debuginfo-install -y grep elfutils-debuginfod`, and these two packages are installed:
* grep-debuginfo
* elfutils-debuginfod-debuginfo

Looks we should use `rpm -q XXX`-`debuginfo` instead of `rpm -q XXX` where `XXX`  is in `{"grep", "elfutils-debuginfod"}`? @psss, @happz and @lukaszachy, right?

**Comment by idorax** [comment]
The latest patch in the following:
```patch
diff --git a/tmt/steps/prepare/install.py b/tmt/steps/prepare/install.py
...<snip>...
-        command = Command('rpm', '-q')
-        command += packages
+        packages_debuginfo = [f'{package}-debuginfo' for package in self.debuginfo_packages]
+        command = Command('rpm', '-q', *packages_debuginfo)
         self.guest.execute(command)
```
is tested manually, and the test result looks good. e.g.
```python
            out: Installed:
            out:   elfutils-debuginfo-0.188-3.fc37.x86_64                                        
            out:   elfutils-debuginfod-debuginfo-0.188-3.fc37.x86_64                             
            out:   elfutils-debugsource-0.188-3.fc37.x86_64                                      
            out:   grep-debuginfo-3.7-4.fc37.x86_64                                              
            out:   grep-debugsource-3.7-4.fc37.x86_64                                            
            out: 
            out: Complete!
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/steps/prepare/install.py(369)install_debuginfo()
-> packages_debuginfo = [f'{package}-debuginfo' for package in self.debuginfo_packages]
(Pdb) l
364  	
365  	        self.guest.execute(command)
366  	
367  	        # Check the packages are installed on the guest because 'debuginfo-install'
368  	        # returns 0 even though it didn't manage to install the required packages
369 B->	        packages_debuginfo = [f'{package}-debuginfo' for package in self.debuginfo_packages]
370  	        command = Command('rpm', '-q', *packages_debuginfo)
371  	        self.guest.execute(command)
372  	
373  	
374  	class InstallYum(InstallDnf):
(Pdb) b 371
Breakpoint 2 at /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/steps/prepare/install.py:371
(Pdb) c
...<snip>...
(Pdb) 
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/steps/prepare/install.py(371)install_debuginfo()
-> self.guest.execute(command)
(Pdb) pp packages_debuginfo
['grep-debuginfo', 'elfutils-debuginfod-debuginfo']
(Pdb) pp command.__dict__
{'_command': ('rpm', '-q', 'grep-debuginfo', 'elfutils-debuginfod-debuginfo')}
(Pdb) c
        Run command: podman exec tmt-012-wGzXNRPU /bin/bash -c 'export TMT_PLAN_DATA=/var/tmp/tmt/run-012/plans/debuginfo/data; export TMT_TREE=/var/tmp/tmt/run-012/plans/debuginfo/tree; rpm -q grep-debuginfo elfutils-debuginfod-debuginfo'
            cmd: rpm -q grep-debuginfo elfutils-debuginfod-debuginfo
            out: grep-debuginfo-3.7-4.fc37.x86_64
            out: elfutils-debuginfod-debuginfo-0.188-3.fc37.x86_64
```

**Comment by psss** [comment]
Failures in `/tests/prepare/recommend` show that the new extra check should not be enabled when `skip == missing`.

**Comment by idorax** [comment]
> Failures in `/tests/prepare/recommend` show that the new extra check should not be enabled when `skip == missing`.

Fixed. @psss, please help to review again, thanks!

**Review by psss — APPROVED** [review]
Now looks good, thanks!

**Pull request merged**
