### PR TITLE
Multi-string help texts converted to multiline strings

### PR DESCRIPTION
**Pull request by happz**
There is a clear distinction: multi-string help texts often involve a trailing or leading whitespace, e.g. a hard space at the end of the first string, to materialize inside the help text once both strings are joined into a single one.

Since this is prone to mistakes, one can easily forget to include a space and produce a visual "typo" in a command help text, and since our `option()` and `field()` helpers support mutliline strings, all multi-string help texts were converted to multiline ones. Involved parties will take care of dedenting a string & reflowing it to fit the help window.

The output should remain unchanged, more or less.

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Review by janhavlin — APPROVED** [review]

**Comment by happz** [comment]
> LGTM. I just have one question. In the `artemis.py` file, I noticed multiple multi-string help texts that follow this pattern:
> 
> https://github.com/teemtee/tmt/blob/1a0cf9d56bb350a62df23b5d4111111289f0b2e0/tmt/steps/provision/artemis.py#L190-L191
> 
> Shouldn't they be edited too? Also, there are multi-string help texts in the `polarion.py` file that should probably be changed too. Or is there a reason why they are not changed?

Definitely, these should be fixed too :) It seems my regex was not good enough to find these.

**Comment by happz** [comment]
@therazix fixed in 7b9963d2

**Review by therazix — APPROVED** [review]

**Review by KwisatzHaderach — APPROVED** [review]

**Review by psss — APPROVED** [review]

**Pull request merged**
