### PR TITLE
Add `tpm` as a new hardware specification key

### LINKED ISSUE #1191: As a user, I'd like to acquire system providing TPM
As mentioned by @kkaarreell today, this is yet another HW requirement out there. See e.g. https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/ for AWS, and there might be ways how to set up VMs accordingly (or request them) for other possible sources.

In any case, adding "requires TPM" should be documented as a HW requirement.

### PR DESCRIPTION
**Pull request by psss**
Let's start with a simple implementation allowing to specify the desired version, use extra dictionary level to allow future extensions if needed.

Fix #1191.

### CODE REVIEW

**Comment by psss** [comment]
As discussed on the hacking session, let's start with a simple implementation for which we have a tangible use case. @kkaarreell, please review to confirm this covers your use case well. Thanks.

**Comment by kkaarreell** [comment]
LGTM for the start.

**Comment by happz** [comment]
@psss I'd propose making corresponding changes to https://github.com/teemtee/tmt/blob/main/tmt/schemas/provision/hardware.yaml in this patch.

**Comment by psss** [comment]
> @psss I'd propose making corresponding changes to https://github.com/teemtee/tmt/blob/main/tmt/schemas/provision/hardware.yaml in this patch.

Good point, json schema updated in 6f65cc16.

**Review by happz — APPROVED** [review]

**Pull request merged**
