### PR TITLE
DO NOT MERGE - trying test suites on top of type annotation

### PR DESCRIPTION
**Pull request by lukaszachy**

### CODE REVIEW

**Comment by lukaszachy** [comment]
Successfully submitted as TJ#6928019

**Comment by lukaszachy** [comment]
@happz This is your type-annotations-staging + my test commits.
Failure in Errata is  TypeError('BasePlugin.wake() takes 1 positional argument but 2 were given')> 

however I will need to check why minute fails because in #1415 it has passed and locally it seems to pass too.

**Comment by lukaszachy** [comment]
@happz local results from tests/full -> all but final 'userdel' PASS. So I am going to ignore userdel at all :)

With that said, unless I introduced some bug by tests commits are GREEN however I need to fix internal errata plugin to work with changed wake() method.
So merge to main should happen only once tmt-redhat is updated (me expects Monday morning).

**Comment by happz** [comment]
> @happz local results from tests/full -> all but final 'userdel' PASS. So I am going to ignore userdel at all :)
> 
> With that said, unless I introduced some bug by tests commits are GREEN however I need to fix internal errata plugin to work with changed wake() method. So merge to main should happen only once tmt-redhat is updated (me expects Monday morning).

Do you mean merging this branch, or `type-annotations-staging`? I plan to add two more patches at least, #1178 + one adding annotations to `base.py`, and I expect plenty of failures from the first run of tests/full on top of *that*.

**Comment by lukaszachy** [comment]
@happz This branch is just for experiments. I meant to merge #1380 to type-annotations-staging branch. Ideally before those breaking changes you mentioned so we have green tests/full and any issue found will come from merged commits afterwards. 

I've tagged you here just to let you know that so far only one issue is with internal plugins and except that all is green and working.


I found one problem to address (makefile assumes tmt is the name of the git) i will fix today. 

I will change targets so and tag people i related PR.

**Comment by thrix** [comment]
Nice, all tests green

**Comment by lukaszachy** [comment]
PR served its purpose. Closing

**Pull request closed without merging**
