### PR TITLE
Add test for TTY state in test environment

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Comment by happz** [comment]
A preliminary patch for https://github.com/teemtee/tmt/pull/1521 - there is no test for TTY setup that would keep me in line when working on TTY/duration changes.

**Review by lukaszachy — COMMENTED** [review]
Nice, however it would be nice to add
a) execute -h tmt --interactive which enables TTY - we shouldn't break that either
b) prepare/finish - we shouldn't change current no-tty state by accident either

**Comment by happz** [comment]
> Nice, however it would be nice to add a) execute -h tmt --interactive which enables TTY - we shouldn't break that either b) prepare/finish - we shouldn't change current no-tty state by accident either

I see. I should move the test elsewhere then, I didn't notice the `finish` is involved.

**Comment by lukaszachy** [comment]
> > Nice, however it would be nice to add a) execute -h tmt --interactive which enables TTY - we shouldn't break that either b) prepare/finish - we shouldn't change current no-tty state by accident either
> 
> I see. I should move the test elsewhere then, I didn't notice the `finish` is involved.

It shouldn't be involved. However everything uses guest.execute so there is a risk we fix the issue there which would affect prepare and finish as well.

**Comment by happz** [comment]
> > > Nice, however it would be nice to add a) execute -h tmt --interactive which enables TTY - we shouldn't break that either b) prepare/finish - we shouldn't change current no-tty state by accident either
> > 
> > 
> > I see. I should move the test elsewhere then, I didn't notice the `finish` is involved.
> 
> It shouldn't be involved. However everything uses guest.execute so there is a risk we fix the issue there which would affect prepare and finish as well.

Sure, makes sense. I suppose `prepare` should get its own chapter, too.

**Comment by happz** [comment]
Refactored & `prepare` and `finish` are now tested as well.

**Comment by happz** [comment]
Blocked by https://github.com/teemtee/tmt/pull/1634

**Comment by happz** [comment]
Adding to 1.19 since it's a prerequisite for https://github.com/teemtee/tmt/pull/1521.

**Review by lukaszachy — APPROVED** [review]

**Pull request merged**
