### PR TITLE
Fix normalization of Plan.context key

### PR DESCRIPTION
**Pull request by happz**
Also dropping `Plan._plan_context`, as this is effectively another name of `context`.

### CODE REVIEW

**Review by psss — APPROVED** [review]
Thanks for fixing this!

**Comment by happz** [comment]
@psss added a couple of checks to the `_normalize_context` method.

**Review by psss — APPROVED** [review]
Nice, looks good!

**Comment by happz** [comment]
And I threw in a schema & a test for invalid dimension values. I spoke about adding it as a patch, but it belongs here as well, so let's get it in the same patch. `tmt` emits a warning, thanks to schema change, but normalization makes strings of everything, leaving the rest to gods of testing.

**Comment by psss** [comment]
Even better, thanks!

**Pull request merged**
