### PR TITLE
Support to import empty key from Makefile

### PR DESCRIPTION
**Pull request by idorax**
fix: #1687

### CODE REVIEW

**Comment by lukaszachy** [comment]
> BTW, do we need to add a unit test case to make sure an empty 'Requires' can be imported successfully?

Yes please. Do not need to be unit test but we need to have a test for this.

**Comment by lukaszachy** [comment]
I believe that just the regexp should be changed to no greedy one + add newline ` regex_require = r'^RhtsRequires:\s*?(.*)\n'`

**Comment by lukaszachy** [comment]
I think that ALL regexp with `\s*` can eat next line, so all regexp should be fixed. (guess we didn't cover empty values in our test suite)

**Comment by lukaszachy** [comment]
Thanks for the changes. Guess we need to change the regexp further. 
I confirmed that current released tmt, when duration empty, indeed leaks next line:
```
	@echo "TestTime:        " >> $(METADATA)
	@echo "RunFor:          r_100149_ybC" >> $(METADATA)
```
converts into `duration: 'RunFor:          r_100149_ybC'`  so we should fix regexps.

However the proposal now keeps spaces so it converts to ,e.g.  `duration: '        5m'`. Now the question is...
Should we call `.strip()` on returned group? Or Improve the regexp?

Another thing I realized too late is that we can use `$` instead of `\n` and as such no need to inject  final `\n`.

For duration for me worked `^TestTime:\s*?(\d.*)$` (added the `\d` so capture group has to start with digit.
Other regexep might start alpha or / (. So how about non space (`\S`) so each `(.*)` changes to `(\S.*)`?

**Comment by idorax** [comment]
> when duration empty, indeed leaks next line: ...
> converts into duration: 'RunFor: r_100149_ybC' so we should fix regexps.

Fixed if duration is empty. 

> However the proposal now keeps spaces so it converts to ,e.g. duration: ' 5m'. Now the question is...
> Should we call .strip() on returned group? Or Improve the regexp?

To make things simple, currently `search_result.group(1).strip()` is used.

**Comment by idorax** [comment]
> For duration for me worked ^TestTime:\s*?(\d.*)$ (added the \d so capture group has to start with digit.
> Other regexep might start alpha or / (. So how about non space (\S) so each (.*) changes to (\S.*)?

Hi @lukaszachy, looks `(\S.*)` doesn't work if `Requires` is empty. e.g.

```python
(Pdb) pp testinfo
('Owner:           Ken Benoit <kbenoit@redhat.com>\n'
...<snip>...
 'Requires:        \n'
 'RhtsRequires:    nc iputils kernel-kernel-test-framework\n'
...<snip>...
 'Destructive:     no\n')
(Pdb) re.findall(r'^Requires:\s*(\S.*)\n', testinfo, re.M)          # Bad
['RhtsRequires:    nc iputils kernel-kernel-test-framework']   
(Pdb) re.findall(r'^Requires:\s*?(\S.*)\n', testinfo, re.M)         # Bad
['RhtsRequires:    nc iputils kernel-kernel-test-framework']
(Pdb) re.findall(r'^Requires:\s*?(.*)\n', testinfo, re.M)           # Good
['        ']
(Pdb) 
```

So, looks `r'^XXX:\s*?(.*)\n'` is the correct one to match `XXX`.

**Comment by idorax** [comment]
> BTW, do we need to add a unit test case to make sure an empty 'Requires' can be imported successfully?
> Yes please. Do not need to be unit test but we need to have a test for this.

Hi @lukaszachy, a simple test is added, please help to review again, thanks!

**Comment by lukaszachy** [comment]
Good point. Which makes me thinking: Why do we match for `\s` in the first place? The format of testinfo is key: value pair per single line. So `\s` eating the newline is the thing we can't allow.

How about `r'^XXX:[ \t]*(.*)$` ?

**Comment by idorax** [comment]
> Good point. Which makes me thinking: Why do we match for `\s` in the first place? The format of testinfo is key: value pair per single line. So `\s` eating the newline is the thing we can't allow.
> 
> How about `r'^XXX:[ \t]*(.*)$` ?

Hi @lukaszachy, `r'^XXX:[ \t]*(.*)$` works well. Please help to take a look again, thanks!

BTW, those lines like `search_result.group(1).strip()`  because `search_result.group(1)` may include trailing whitespace, if you prefer to use `rstrip()`, please let me know, I'll update accordingly.

**Comment by idorax** [comment]
The test failures of `centos-stream-9-x86_64` look like:
* https://artifacts.dev.testing-farm.io/e0f0e111-9a7d-4ce2-acdd-f7adbd1b8c6a/
```
Failed to run command: export TMT_PLAN_DATA=/tmp/tmp.ttWuYU6uQj/plans/default/data; uname -r Reason: Command returned '255'.

stderr (1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: can only create exec sessions on running containers: container state improper
```

@lukaszachy and @psss, any idea?

**Comment by psss** [comment]
For reference: With podman-4.3.1-1.el9 it works, with podman-4.3.1-3.el9 from `testing-farm-tag-repository` it fails.

**Review by psss — APPROVED** [review]
Looks good, thanks for fixing this!

**Review by lukaszachy — APPROVED** [review]
Thank you for the fix.

**Pull request merged**
