### PR TITLE
Enable OpenScanHub scans

### PR DESCRIPTION
**Pull request by siteshwar**
... as it is now able to resolve dynamic dependencies.

### CODE REVIEW

**Comment by siteshwar** [comment]
https://github.com/packit/packit/discussions/2371#discussioncomment-11154346

This pull request should be kept on hold.

**Comment by siteshwar** [comment]
The checks are [passing](https://github.com/teemtee/tmt/pull/3342/checks?check_run_id=32590518666) now, so this can be merged.

**Review by psss — APPROVED** [review]

**Pull request merged**
