### PR TITLE
Outline specification for using ansible roles

### PR DESCRIPTION
**Pull request by psss**
For now just rough draft of how roles could be specified. It seems
the `ansible-galaxy` command already supports fetching roles from
git repositories so the implementation should not be hard I guess.

https://galaxy.ansible.com/docs/using/installing.html

### CODE REVIEW

**Comment by psss** [comment]
As discussed on the hacking session, here's the kick-off pull request for the role support in ansible `prepare` step. @thrix, @happz, @FrNecas, @lukaszachy, @pvalena, please have a look.

**Comment by thrix** [comment]
Another idea from the hacking session: instead of adding `role` or `collections` keywords to tmt, I think it would be more reasonable to provide ansible-galaxy requirements file instead, which supports both, it is more standard and also we should be better covered future-wise.

```
# Install requirements via ansible-galaxy and run given playbook
prepare:
    how: ansible
    requirements: ansible/requirements.yml 
    playbook: ansible/playbooks/test.yml
```

**Comment by pcahyna** [comment]
@thrix that would work. Several remarks:

- it precludes installing collections from RPMs because you can't specify them in requirements - probably that's not a big problem though and if you want it, I suppose you can list the RPM providing the desired collection as a RPM requirement elsewhere
- it has the advantage of applying an arbitrary playbook, not just a role, but you then need to specify a standard for the `hosts:` entry in the playbook (as a bad example, STI did not tell you what to put there, so some people used `localhost`, some used `all` ... ).
- one should be able to specify variables for the playbook run in order to be able to write generic playbooks (this applied to the original proposal using roles as well)
- one should be prepared to the possibility of specifying a playbook relative to a collection (embedded in a collection) - https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#using-a-playbook-from-a-collection - but his is supported only since Ansible 2.11, so I would say do not rely on it yet.

**Comment by thrix** [comment]
> @thrix that would work. Several remarks:
> 
> * it precludes installing collections from RPMs because you can't specify them in requirements - probably that's not a big problem though and if you want it, I suppose you can list the RPM providing the desired collection as an RPM requirement elsewhere

yep, that should not be a problem, we have for rpm requires a dedicated step

> * it has the advantage of applying an arbitrary playbook, not just a role, but you then need to specify a standard for the `hosts:` entry in the playbook (as a bad example, STI did not tell you what to put there, so some people used `localhost`, some used `all` ... ).

I guess that is just a documentation thing, I would expect users to use `hosts: all` for their playbooks ...

> * one should be able to specify variables for the playbook run to be able to write generic playbooks (this applied to the original proposal using roles as well)

+1 this is what I mentioned in the hacking session

> * one should be prepared for the possibility of specifying a playbook relative to a collection (embedded in a collection) - https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#using-a-playbook-from-a-collection - but his is supported only since Ansible 2.11, so I would say do not rely on it yet.

right, but that is automatic, once we pass to ansible-playbook like `my_namespace.my_collection.playbook1` it will just work (ansible 2.11+ will recognize it correctly)? i.e. nothing needed on the `tmt` side?

**Pull request closed without merging**
