### PR TITLE
Update all linters to their most recent versions

### PR DESCRIPTION
**Pull request by happz**
Before wrapping up the type annotations, make sure we can squeeze the most out out involved tools.

### CODE REVIEW

**Comment by thrix** [comment]
@happz maybe this should be kinda automatic chm, https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/

**Review by thrix — APPROVED** [review]
LGTM

**Comment by happz** [comment]
> @happz maybe this should be kinda automatic chm, https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/

IIUIC, it can be set up, GH actions would create a PR with changes. Sounds nice to me, I can set it up later if it'd be fine with maintainers, at this moment I'm in no rush, I'd be fine with having these up-to-date *after* we're done with annotations PR.

**Comment by happz** [comment]
> > > @happz maybe this should be kinda automatic chm, https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/
> > 
> > 
> > IIUIC, it can be set up, GH actions would create a PR with changes.
> 
> So what's the point of freezing the exact versions and creating pull requests with regular/frequent updates when compared to just using the latest available version from `main`? Will someone be checking what changes were done and if they are safe? Or?

WRT freezing exact versions - I find great value in predictability, reproducibility. Everyone running `pre-commit` would use the exact same version of tools, no matter what their delopers push into their repositories. I would vote for not giving this precious value up.

The bump to newer versions would happen by a PR which would contain not just changes to `.pre-commit-config.yaml`, but also any changes to tmt code made by new versions of tools, therefore the review of changes could happen right there (tests included).

**Comment by psss** [comment]
@happz, why is this marked as blocked? I don't see any obstacles before enabling the latest linter features and fixing issues.

**Comment by psss** [comment]
To be merged only after #1457 is done.

**Comment by psss** [comment]
#1457 almost merged, time to refresh this one as well?

**Comment by happz** [comment]
> #1457 almost merged, time to refresh this one as well?

Correct, I'll look into it. There are a few other steps needed to wrap up #1182, including the linters, I'll work on all of those once #1457 lands.

**Comment by happz** [comment]
@psss rebased, ready for merge.

**Comment by psss** [comment]
Thanks for the update, looks good!

**Pull request merged**
