### PR TITLE
Allow `urllib3` 2.x

### PR DESCRIPTION
**Pull request by hroncok**
Followup for 7bbb340d89dd816bfd8d3ab6d77808882d837454

### CODE REVIEW

**Comment by martinhoyer** [comment]
Looks good to me.  
Small caveat being rawhide using 1.26.x, meaning pip-installations will use different version than rpms for now. I don't think it's a problem though. 
urllib3 2.0 migration guide: https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#migrating-as-a-package-maintainer

**Comment by hroncok** [comment]
This is motivated by an in-progress rawhide update to urllib3 2.x

**Comment by happz** [comment]
Something to include in 1.31, @psss ?

**Review by thrix — APPROVED** [review]
LGTM

**Comment by lukaszachy** [comment]
IMO safe to include, unit tests pass (executed manually and forced newer urllib3 and requests..)

**Review by lukaszachy — APPROVED** [review]

**Review by psss — APPROVED** [review]

**Comment by psss** [comment]
> Something to include in 1.31, @psss ?

Yeah, make sense.

**Pull request merged**
