### PR TITLE
Simplify the packit configuration

### PR DESCRIPTION
**Pull request by LecrisUT**
Follow-up to https://github.com/teemtee/tmt/pull/3024 now that https://github.com/packit/packit/pull/2378 is merged.

### CODE REVIEW

**Comment by LecrisUT** [comment]
@martinhoyer can you /packit build this one?

**Review by psss — APPROVED** [review]
Thanks for simplifying this! Looks good and the overall resulting config seems to be identical with the orignal one (except for some defaults, which is expected).

**Pull request merged**
