### PR TITLE
Expose tmt version as an environment variable

### PR DESCRIPTION
**Pull request by idorax**
Fixes: #2267

### CODE REVIEW

**Comment by happz** [comment]
@idorax please, add the variable to `README.rst` as well, there's a list of variables exposed by tmt, this one should be documented there.

**Comment by happz** [comment]
> > @idorax please, add the variable to `README.rst` as well, there's a list of variables exposed by tmt, this one should be documented there.
> 
> Just added `TMT_VERSION` to `Step Variables`, not sure it should be added to `Command Variables`. @happz, please correct me if it's incorrect, thanks!

Correct, no command variable as those are **accepted** by tmt - not the case of `TMT_VERSION` :)

**Review by happz — APPROVED** [review]

**Comment by idorax** [comment]
Hi @happz, looks the test failures from `testing-farm:fedora-39-x86_64` are not relevant to this patch. e.g.

* [/tests/execute/upgrade/simple](https://artifacts.dev.testing-farm.io/062bec8a-16d3-4668-a1b4-26431780de35/work-advanced6jn869_u/plans/features/advanced/execute/data/guest/default-0/tests/execute/upgrade/simple-5/output.txt)
  ```
        no package provides beakerlib
        Fedora 37 - x86_64                              535  B/s | 3.3 kB     00:06
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        stderr (4 lines)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Errors during downloading metadata for repository 'fedora':
          - Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-37&arch=x86_64&countme=1 (IP: 8.43.85.67)
          - Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-37&arch=x86_64 (IP: 8.43.85.67)
        Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-37&arch=x86_64 (IP: 8.43.85.67)
  ```
* [ /tests/prepare/install](https://artifacts.dev.testing-farm.io/062bec8a-16d3-4668-a1b4-26431780de35/work-prepareyx19830h/plans/features/steps/prepare/execute/data/guest/default-0/tests/prepare/install-5/output.txt)
  ```
        Downloading Packages:
        The downloaded packages were saved in cache until the next successful transaction.
        You can remove cached packages by executing 'dnf clean packages'.
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        stderr (2 lines)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error: Error downloading packages:
          Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 (IP: 8.43.85.67)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        :: [ 02:14:16 ] :: [   FAIL   ] :: Command 'tmt run -adddvvvr plan --name exclude' (Expected 0, got 2)
  ```

**Review by lukaszachy — APPROVED** [review]

**Pull request merged**
