### PR TITLE
Fix expansion of envvar starting with "@" in fmf nodes

### PR DESCRIPTION
**Pull request by happz**
`$FOO` fed with `FOO: @bar` resulted in `$@bar` instead of `@bar`.

Reported in https://github.com/teemtee/tmt/issues/2654

Pull Request Checklist

* [x] implement the feature
* [x] extend the test coverage

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]

**Review by psss — APPROVED** [review]
Thanks for fixing this!

**Comment by happz** [comment]
> Seems that `/tests/discover/parametrize` fails on fetching a parametrized repo. @happz, could you please have a look?

Hopefully addressed in 36eb9783

**Comment by psss** [comment]
> Hopefully addressed in [36eb978](https://github.com/teemtee/tmt/commit/36eb978363a05d4c02809b70d2f7e7dfb4c84555)

Yeah, this looks good, thanks!

**Pull request merged**
