### PR TITLE
Emit only non-default keys when constructing a test from `execute`

### PR DESCRIPTION
**Pull request by happz**
This should prevent unexpected warnings because default *internal* values are not allowed by JSON schema guarding user input.

Related to #1546.

### CODE REVIEW

**Comment by happz** [comment]
Tests are failing, and the solution in this patch is far from perfect. The correct way would be to use `to_spec()` method as defined in #1522.

**Comment by psss** [comment]
Test results look better, though `/tests/discover/duration` is still failing.

**Comment by happz** [comment]
> Test results look better, though `/tests/discover/duration` is still failing.

Fixed a couple of minutes ago, the test expects `duration: 1h` to appear in the output even though `1h` is the default, therefore the key could have been omited.

**Review by psss — APPROVED** [review]
Looks good. Thanks for the fix!

**Pull request merged**
