### PR TITLE
Translate `beaker.pool` hardware requirement properly for `mrack`

### PR DESCRIPTION
**Pull request by skycastlelily**
Related to https://github.com/teemtee/tmt/issues/2346

Pull Request Checklist

* [x] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Comment by happz** [comment]
@skycastlelily I think that with the last push, you overwritten the original changes adding the implementation to `tmt/steps/provision/mrack.py`. All that's left now is the operator update (pre-commit & mypy complain about the list vs tuple, BTW).

It's really better to avoid force pushes, one can easily lose changes. We recommend adding new changes to PRs with new commits, e.g. named "squash: ...", eventually they would be squashed before merging, when all is done.

**Comment by happz** [comment]
>> I think that with the last push, you overwritten the original changes
>> adding the implementation
>
> That's on purpose, I already implemented beaker.pool in merged #3074 , after thinking twice, I prefer to keep the implementation way as it is.

I see, makes sense.

BTW pre-commit is still failing, that's not related to this discussion, and should be fixed.

**Comment by skycastlelily** [comment]
Updated^^

**Review by happz — APPROVED** [review]

**Review by therazix — APPROVED** [review]

**Comment by psss** [comment]
All failures are irrelevant, merging.

**Pull request merged**
