### PR TITLE
Underline `try` menu keys

### PR DESCRIPTION
**Pull request by lukaszachy**
Better visibility for color schemas as solarized

image

Fix: #2564

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Review by psss — CHANGES_REQUESTED** [review]
Hmmm, to me it now seems much less readable because of the square brackets. Could we possibly use something a bit less intrusive? Like underline? Tried it and it does not look bad:

image

Could this be a kind of compromise solution?

**Comment by happz** [comment]
> Hmmm, to me it now seems much less readable because of the square brackets. Could we possibly use something a bit less intrusive? Like underline? Tried it and it does not look bad:
> 
> image
> 
> Could this be a kind of compromise solution?

+1 to underscore, LGTM.

**Comment by lukaszachy** [comment]
@psss Why less intrusive though? 
IMO as a new `tmt try` user I need clear instructions what to do and having it in brackets is a really clear way.
One I learn to use it I don't read the menu at all and just waiting to see the prompt.

**Comment by psss** [comment]
> @psss Why less intrusive though?

By that I meant that the original word is crippled by the square brackets so much that the quick-glimpse reading does not work any more. The words seem to me like broken.

> IMO as a new `tmt try` user I need clear instructions what to do and having it in brackets is a really clear way.

I would say that the the three different characteristics (color, boldness and underline) make it quite clear to identify the desired key.

> Once I learn to use it I don't read the menu at all and just waiting to see the prompt.

Which also means that you only have to look for the underlined letter at the beginning and once you get accustomed you can happily ignore the formatting.

**Comment by lukaszachy** [comment]
> By that I meant that the original word is crippled by the square brackets so much that the quick-glimpse reading does not work any more. The words seem to me like broken.

I see, it could also break screen readers. Changed in cbf5a2ac (and rebased)

**Review by psss — APPROVED** [review]

**Pull request merged**
