### PR TITLE
Introduce "topology" addresses for guests

### PR DESCRIPTION
**Pull request by happz**
Besides a current "guest" attribute - now called "primary address", the patch adds "topology address" for guests to use when talking to each other. As of now, the topology address of a guest is the same as its primary address, but we expected that to change.

Related to https://github.com/teemtee/tmt/issues/2620

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Review by psss — APPROVED** [review]
Looks good, thanks!

**Comment by psss** [comment]
@happz, do you plan to add some docs?

**Comment by happz** [comment]
> @happz, do you plan to add some docs?

@psss probably not, I suppose we will have tests when the actual topology addresses arrive.

**Review by janhavlin — APPROVED** [review]

**Pull request merged**
