### PR TITLE
Update pre-commit checks and add a couple of new ones

### PR DESCRIPTION
**Pull request by happz**
Namely prevent commits to `main` branch, check for merge/rebase conflict markers in files, and look for private keys.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]
I'm surprised no fixup was necessary with checks added.

**Comment by martinhoyer** [comment]
Security-related checks note:
[Skjold](https://github.com/twu/skjold) doesn't look like being suitable for pre-commit, as it checks .lock or .requirements.txt files.
Perhaps it would could be incorporated to the "without site packages" test.
pyproject.toml:
```
[tool.skjold]
sources = ["pyup", "gemnasium"] 
```
```
$ pip install .[all] skjold
$ pip list --exclude pip --format=freeze | skjold audit -
No vulnerable packages found!
```

**Comment by lukaszachy** [comment]
> aand I don't see any other suitable (security) pre-commit hooks, so lgtm as is.

@martinhoyer btw, could you tick the approval button - that would make github reviews counter happier.

**Comment by psss** [comment]
> I'm not a reviewer on this one, so there is no approve button, but I'll keep it in mind for other PRs, thanks!

@martinhoyer, I believe, everybody should be able to provide review. Even if not member of the organization / write access to the repo. See my [recent review](https://github.com/beakerlib/beakerlib/pull/171#pullrequestreview-1979281433) on the beakerlib pull request. You get a gray tick but the review is there.

**Comment by psss** [comment]
> there is no approve button

You go to the `Files changed` tab and there's the `Review changes` button.

**Comment by martinhoyer** [comment]
> > there is no approve button
> 
> You go to the `Files changed` tab and there's the `Review changes` button.

Learning every day 🫡 Thanks.
(technically I wasn't wrong about the approve button though hehe)

**Review by martinhoyer — APPROVED** [review]

**Pull request merged**
