### PR TITLE
Adds a test for fmf id parsing and normalization

### PR DESCRIPTION
**Pull request by happz**
Some refs may look like integers, commit IDs, for example. With short
commit IDs used frequently the chances are even higher. Since the `ref`
field should be a string, tmt is expected to complain when being fed an
invalid ref.

### CODE REVIEW

**Comment by pcahyna** [comment]
Does it mean that `0x8deadbeaf8`  will be converted to 609530669816 which then represents commit id `"609530669816"`?

Generally speaking, I believe that to make things easier for the users one should have simple and clean rules (when you mean a string, write a string) instead of introducing "helpful" rules for implicit conversions.

**Comment by pcahyna** [comment]
Worse, leading 0s will be interpreted as indication that the number is octal.

**Comment by happz** [comment]
> Does it mean that `0x8deadbeaf8` will be converted to 609530669816 which then represents commit id `"609530669816"`?

That should not be happening. The issue is with integer-looking refs, base 10, like `12345678`. YAML parser would ingest these and present them as actual integers to tmt internals, while other refs would be presented as strings. The conversion tmt code performs is applied to the first kind, turning `12345678` into `"12345678"`. tmt should not need to touch `8deadbeef8` refs, because those would already be handed as `"8deadbeef8"`.

Note that the `ref` value is *not* `0x8deadbeef8`, but `8deadbeef8`, no leading `0x` that would hint YAML parser it's a base 16 integer. As a field, `ref` should be a string, and one possible solution would be to ask users to enclose all `ref` values in quotes, `ref: "12345678"`. The conversion code makes it slightly easier for users by dealing with those without quotes transparently.

> 
> Generally speaking, I believe that to make things easier for the users one should have simple and clean rules (when you mean a string, write a string) instead of introducing "helpful" rules for implicit conversions.

**Comment by pcahyna** [comment]
> That should not be happening.

It could, if the user writes `0x8deadbeaf8` explicitly. Sure, you can say that nobody would do that, but I find the result unexpected.

**Comment by happz** [comment]
> > That should not be happening.
> 
> It could, if the user writes `0x8deadbeaf8` explicitly. Sure, you can say that nobody would do that, but I find the result unexpected.


Yes, git commit ID or hash can be interpreted as a hexadecimal number, but, IIRC, no git implementation or service ever displays commit IDs with leading `0x`. This means if users write a `ref: 0xdeadbeef`, they must have added the `0x` on their own. Why would anyone do that? No guarantees, "warranty void if removed", etc.

> 
> EDIT: anyway, I think that leading 0s are a much more serious problem than this arguably theoretical consideration.

Now, this I consider a more serious issue than folks adding `0x` to refs. I'm not sure about commit IDs with leading zeros, but there for sure can be branches and tags like `0000012345`, and YAML would indeed deliver them as octal numbers to tmt internals. I see no defense other than enclosing such a value in quotes, and now the question is, shouldn't this become a mandatory step? `00123456` would indeed lead to unexpected behavior, and for tmt code it's impossible to realize the original value wasn't `42798`...

@lukaszachy this patch was motivated by your comment https://github.com/teemtee/tmt/pull/1591#issuecomment-1282361049, anything you'd like to add? Looking for an agreement here. @psss

**Comment by pcahyna** [comment]
> > EDIT: anyway, I think that leading 0s are a much more serious problem than this arguably theoretical consideration.
> 
> Now, this I consider a more serious issue than folks adding `0x` to refs. I'm not sure about commit IDs with leading zeros, 

Aren't they just SHA1 values? i don't think anything prevents SHA1 from returning a hex string with a leading zero. Try
```sh
for i in `seq 1 100`; do echo $i | sha1sum | grep ^0; done
``` 

> but there for sure can be branches and tags like `0000012345`, and YAML would indeed deliver them as octal numbers to tmt internals. I see no defense other than enclosing such a value in quotes, and now the question is, shouldn't this become a mandatory step? `00123456` would indeed lead to unexpected behavior, and for tmt code it's impossible to realize the original value wasn't `42798`...

Note that even without the special syntax for octals this kind of normalization would not work. If there can be refs like `0000012345`, how would you realize that the original value was not  `12345`? Note that decimal numbers are padded with numbers to the left, but commit IDs can be shortened at the right side. So the number representation 00012345 (decimal) is equivalent to 12345, but the commit ID `12345` is not equivalent to the commit ID `00012345` (in contrast `12345000` can be shortened to just  `12345` if unique).

**Comment by happz** [comment]
After a discussion, we settled on forcing users to stick with strings. This means no changes in schema or code are needed, so I edited my PR, leaving just the test to verify tmt does complain about invalid refs.

**Review by psss — APPROVED** [review]
Thanks for improving this. Looks good. Added a couple of changes in 4d31845c, just minor improvements. Please, have a look if everything is ok.

**Pull request merged**
