### PR TITLE
Dry mode for tests export --nitrate

### PR DESCRIPTION
**Pull request by lukaszachy**
Including --create

Will print what would be done but no write to tcms should happen (nor bugzilla)

### CODE REVIEW

**Comment by lukaszachy** [comment]
@jscotka Is there a way how to see/store also requested data in requre cassette? Eg. arguments of xmlrpc call...

**Comment by psss** [comment]
Two tests failed: It seems that integration tests are not happy about the change.

**Comment by lukaszachy** [comment]
@psss. oops, my fault. I need to change summary strings

**Comment by psss** [comment]
One (hopefully) last adjustment needed because of an extra failing test on `centos-stream-8`:

```
        self.assertIn(
            "summary: tmt /new_testcase - This i",
>           self.runner_output.stdout)
E       AttributeError: 'Result' object has no attribute 'stdout'
```

Which seems to be caused by an old version of `click` which does not have `stdout` (yet) but only has `output` attribute supported in the `Results` object.

**Pull request merged**
