### PR TITLE
Move `tag` and `tier` to common core attributes

### PR DESCRIPTION
**Pull request by psss**
It makes sense to allow using `tag` and `tier` keys for filtering
plans and stories as well. Let's move them to `core` attributes.

### CODE REVIEW

**Comment by psss** [comment]
As for now, only the specification adjustments are covered in the pull request. Actual implementation changes to be done once all important typing changes land in the `main` branch. @kkaarreell, fyi.

**Comment by lukaszachy** [comment]
Nice, will be definitely  useful.

**Comment by psss** [comment]
Should be ready for review: Implementation moved, schemas updated, added some test coverage. I guess we could still add it to `1.17` unless there is conflict with typing annotations.

**Review by thrix — APPROVED** [review]
LGTM

**Pull request merged**
