### PR TITLE
Print escaped command suitable for manual debugging

### PR DESCRIPTION
**Pull request by happz**
Includes a small refactoring of "log command" code.

### CODE REVIEW

**Comment by thrix** [comment]
@happz Copy paste version is cool, but I wonder what sense does it make to print both versions ...

```
        Run command 'rsync -R -r -z --links --safe-links --protect-args -e ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /'
        Copy/paste version: rsync -R -r -z --links --safe-links --protect-args -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b' root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /
```

I would be perfectly happy with a command, which is copy pastable, instead of printing 2 versions ...

```
        Run command: rsync -R -r -z --links --safe-links --protect-args -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b' root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /
```

**Review by thrix — CHANGES_REQUESTED** [review]
I would rather mitigate duplication and make the `Run command:` string copy-paste-able

**Comment by happz** [comment]
> @happz Copy paste version is cool, but I wonder what sense does it make to print both versions ...
> 
> ```
>         Run command 'rsync -R -r -z --links --safe-links --protect-args -e ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /'
>         Copy/paste version: rsync -R -r -z --links --safe-links --protect-args -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b' root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /
> ```
> 
> I would be perfectly happy with a command, which is copy pastable, instead of printing 2 versions ...
> 
> ```
>         Run command: rsync -R -r -z --links --safe-links --protect-args -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10028 -i/var/tmp/tmt/run-090/plans/example/provision/default-0/id_ecdsa -S/run/user/1000/tmt/tmpja7v5o0b' root@127.0.0.1:/var/tmp/tmt/run-090/plans/example/data /
> ```

I agree, I'd be interested in hearing the opinions of others, like @psss or @lukaszachy. Having a copy & paste-able version is what I'm used to, and it became handy while working on tests during step data conversion.

**Comment by lukaszachy** [comment]
I like @thrix 's single line idea. Would be nice to have boundary for the command though. Especially when `.` will be as a last character it might be difficult to spot where command ends (or if it is a fancy dot for end of the sentence)

**Comment by happz** [comment]
> I like @thrix 's single line idea. Would be nice to have boundary for the command though. Especially when `.` will be as a last character it might be difficult to spot where command ends (or if it is a fancy dot for end of the sentence)

This is what we did in gluetool, exactly to improve readability, to clearly mark what command is and isn't:

```
[15:31:51] [D] runnable (copy & paste):
---v---v---v---v---v---
/bin/bash -c 'command -v restraint'
---^---^---^---^---^---
```

I wanted to start small, and since boundaries like this are not really something tmt uses in its logging, I didn't even think about adding them - but I'd love to do so, it makes absolute sense to me to mark things like this :)

**Comment by thrix** [comment]
> > I like @thrix 's single line idea. Would be nice to have boundary for the command though. Especially when `.` will be as a last character it might be difficult to spot where command ends (or if it is a fancy dot for end of the sentence)
> 
> This is what we did in gluetool, exactly to improve readability, to clearly mark what command is and isn't:
> 
> ```
> [15:31:51] [D] runnable (copy & paste):
> ---v---v---v---v---v---
> /bin/bash -c 'command -v restraint'
> ---^---^---^---^---^---
> ```
> 
> I wanted to start small, and since boundaries like this are not really something tmt uses in its logging, I didn't even think about adding them - but I'd love to do so, it makes absolute sense to me to mark things like this :)

I will be happy with this, although I am not certain how it will work out with the indentation `tmt` is using.

**Comment by happz** [comment]
Ok, there are two use cases in the original code:

* when `message` is given, the message is printed out, no command
* when `message` is not given, a message is constructed which contains a command.

I added the copy & paste-able log entry to both, but the "duplication" can be observed only in the second case when a `message` is not given by a caller. The command (not the copy & pasteable one) is also part of an error message that might be raised.

How shall I handle this duality? I can of course print just the copy & pasteable command, shall I simply use the copy & pasteable version everywhere the simpler one was used?

How about this implementation?

```python
        # A bit of logging - command, default message, error message for later...
        if isinstance(command, (list, tuple)):
            printable_command = ' '.join(shlex.quote(s) for s in command)

        else:
            printable_command = command

        if message:
            self.debug(message, level=2)

        self.debug(
            'Running command',
            f'---v---v---v---v---v---\n{printable_command}\n---^---^---^---^---^---',
            level=3)

        message = f"Failed to run command '{printable_command}'"
```

Lead to the following output:

```
Sync the worktree to '/var/tmp/tmt/run-057/plans/features/core/tree'.
Running command: 
    ---v---v---v---v---v---
    rsync -ar --exclude .git /home/happz/git/tmt/ /var/tmp/tmt/run-057/plans/features/core/tree
    ---^---^---^---^---^---
Command returned '7'.

Failed to run command 'rsync -ar --exclude .git /home/happz/git/tmt/ /var/tmp/tmt/run-057/plans/features/core/tree' Reason: Command returned '7'.
```

**Review by thrix — APPROVED** [review]
LGTM

**Comment by psss** [comment]
I'm not sure about adding the extra boundaries. Instead of one line we get four for each command which makes (from my view) the readability much worse. And I'd say the copy & paste use case is far less common then just reviewing the logs. For comparison:

```
Execute command 'cat /etc/lsb-release' on guest '127.0.0.1'.
Running command: 
    ---v---v---v---v---v---
    ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g root@127.0.0.1 'export TMT_PLAN_DATA=/var/tmp/tmt/run-081/plans/example/data; cat /etc/lsb-release'
    ---^---^---^---^---^---
err: cat: /etc/lsb-release: No such file or directory
Command returned '1'.
Execute command 'cat /etc/redhat-release' on guest '127.0.0.1'.
Running command: 
    ---v---v---v---v---v---
    ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g root@127.0.0.1 'export TMT_PLAN_DATA=/var/tmp/tmt/run-081/plans/example/data; cat /etc/redhat-release'
    ---^---^---^---^---^---
out: Fedora release 36 (Thirty Six)
Execute command 'uname -r' on guest '127.0.0.1'.
Running command: 
    ---v---v---v---v---v---
    ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g root@127.0.0.1 'export TMT_PLAN_DATA=/var/tmp/tmt/run-081/plans/example/data; uname -r'
    ---^---^---^---^---^---
out: 5.17.5-300.fc36.x86_64
```
And before:

```
Execute command 'cat /etc/lsb-release' on guest '127.0.0.1'.
Run command 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-082/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpel5041oz root@127.0.0.1 export TMT_PLAN_DATA=/var/tmp/tmt/run-082/plans/example/data; cat /etc/lsb-release'.
err: cat: /etc/lsb-release: No such file or directory
Command returned '1'.
Execute command 'cat /etc/redhat-release' on guest '127.0.0.1'.
Run command 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-082/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpel5041oz root@127.0.0.1 export TMT_PLAN_DATA=/var/tmp/tmt/run-082/plans/example/data; cat /etc/redhat-release'.
out: Fedora release 36 (Thirty Six)
Execute command 'uname -r' on guest '127.0.0.1'.
Run command 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-082/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpel5041oz root@127.0.0.1 export TMT_PLAN_DATA=/var/tmp/tmt/run-082/plans/example/data; uname -r'.
out: 5.17.5-300.fc36.x86_64
```

This gets much much longer for things like `rstrnt-*` scripts preparation:

```
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort' to '/usr/local/bin/tmt-abort' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort root@127.0.0.1:/usr/local/bin/tmt-abort
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort' to '/usr/local/bin/rstrnt-abort' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort root@127.0.0.1:/usr/local/bin/rstrnt-abort
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort' to '/usr/local/bin/rhts-abort' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-abort root@127.0.0.1:/usr/local/bin/rhts-abort
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit' to '/usr/local/bin/tmt-file-submit' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit root@127.0.0.1:/usr/local/bin/tmt-file-submit
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit' to '/usr/local/bin/rstrnt-report-log' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit root@127.0.0.1:/usr/local/bin/rstrnt-report-log
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit' to '/usr/local/bin/rhts-submit-log' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit root@127.0.0.1:/usr/local/bin/rhts-submit-log
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit' to '/usr/local/bin/rhts_submit_log' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-file-submit root@127.0.0.1:/usr/local/bin/rhts_submit_log
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot' to '/usr/local/bin/tmt-reboot' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot root@127.0.0.1:/usr/local/bin/tmt-reboot
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot' to '/usr/local/bin/rstrnt-reboot' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot root@127.0.0.1:/usr/local/bin/rstrnt-reboot
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot' to '/usr/local/bin/rhts-reboot' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-reboot root@127.0.0.1:/usr/local/bin/rhts-reboot
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result' to '/usr/local/bin/tmt-report-result' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result root@127.0.0.1:/usr/local/bin/tmt-report-result
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result' to '/usr/local/bin/rstrnt-report-result' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result root@127.0.0.1:/usr/local/bin/rstrnt-report-result
    ---^---^---^---^---^---
Copy '/home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result' to '/usr/local/bin/rhts-report-result' on the guest.
Running command: 
    ---v---v---v---v---v---
    rsync -p --chmod=755 -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /home/psss/git/tmt/tmt/steps/execute/scripts/tmt-report-result root@127.0.0.1:/usr/local/bin/rhts-report-result
    ---^---^---^---^---^---
Push workdir to guest '127.0.0.1'.
Running command: 
    ---v---v---v---v---v---
    rsync -R -r -z --links --safe-links --delete -e 'ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p10040 -i/var/tmp/tmt/run-081/plans/example/provision/default-0/id_ecdsa -S/run/user/12559/tmt/tmpheaxkf6g' /var/tmp/tmt/run-081/plans/example root@127.0.0.1:/
    ---^---^---^---^---^---
```

If it would be a common use case to copy & paste those `rsync` commands I could probably bear it. But my impression that for 99% percent of the log review time this will just cause unnecessary clutter. Could we keep just one line per command? Maybe, indenting the actual command one more level deeper?

**Comment by happz** [comment]
> If it would be a common use case to copy & paste those `rsync` commands I could probably bear it. But my impression that for 99% percent of the log review time this will just cause unnecessary clutter. Could we keep just one line per command? Maybe, indenting the actual command one more level deeper?

I spent hours copying & pasting commands into another terminal while debugging changes I made in step data patches. So, yeah, 99% of the log review time it's not needed, but when it is, it's absolutely painful to *not* have the copy & pasteable version at hand. I do understand the verbosity aspect, on the other hand, the less verbose logging output has very limited use since all but the simplest commands logged are basically read-only, and it's usually the complicated ones that a) fail and b) are a PITA to get right when copied to become a reproducer while debugging the issue.

With that on my mind, I'd like to have the chance to see what command tmt actually executed, not just some abridged and "good enough for humans" version when needed. Moving it to a deeper verbosity level would work for me - it's not that important for me whether it's `-d` or `-ddddddd` material - there are simply times when seeing exactly what was executed is absolutely crucial for debugging effort.

So, how shall we proceed? I could live without boundaries, they were requested by @lukaszachy (and we use them heavily in Gluetool and modules, so no problem with me), so a single line - but quoted correctly - with `level=3` would be acceptable?

**Comment by lukaszachy** [comment]
@psss I'd say that rstrnt-* comman preparation is too noisy and until now just no one complained (but log is unreadable already)
Personally I liked the single backquote as start/end token however it might be part of the command. Without boundaries it it easy to overlook last argument.

But it's final call of @psss as tmt architect ;)

**Comment by psss** [comment]
Thanks much for sharing your thoughts. I'd say let's go definitely with one-line. Regarding boundaries: Wouldn't it be better to be able to triple-mouse-click and execute with just slight command line adjustment like removing the prefix?

> simply announce "anything after `Run command:` is _the_ command".

This would exactly cover that: Triple-mouse-click, remove two words, go! I find this a bit better than having to remove the suffix boundary as well. Or... what about this one?

    [ command ]; echo "this is the command to be executed with whatever `escaping` it has"

A bit of a shell hack to provide at least some tag-like hint that this is the pastable command but it would be: Triple-click, paste and go!

**Comment by happz** [comment]
> Thanks much for sharing your thoughts. I'd say let's go definitely with one-line. Regarding boundaries: Wouldn't it be better to be able to triple-mouse-click and execute with just slight command line adjustment like removing the prefix?
> 
> > simply announce "anything after `Run command:` is _the_ command".
> 
> This would exactly cover that: Triple-mouse-click, remove two words, go! I find this a bit better than having to remove the suffix boundary as well. Or... what about this one?
> 
> ```
> [ command ]; echo "this is the command to be executed with whatever `escaping` it has"
> ```
> 
> A bit of a shell hack to provide at least some tag-like hint that this is the pastable command but it would be: Triple-click to select the whole line, paste and go!

I'd opt for the first option then, everything after `Run command:` is the command, full stop. I would stay away from shell hacks unless we have to/want to include them :)

**Comment by happz** [comment]
Ok, updated & rebased.

**Review by psss — APPROVED** [review]
Thanks for the adjustments. I just kept the `Run command` wording.

**Pull request merged**
