### PR TITLE
Add a linter for Jinja2 templates

### PR DESCRIPTION
**Pull request by happz**
Maybe we would add also a formatter (same tool, different check and options), but starting small with linters. Few very minor issues reported, plus a genuine one.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Comment by martinhoyer** [comment]
Nice, have you also tried [j2lint](https://github.com/aristanetworks/j2lint)? 
```
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
      - id: j2lint
        args: [--ignore, 'jinja-statements-indentation', 'jinja-variable-lower-case', --]
```

Of course if the intention is to also have formatter, then it's a moot point, but I guess it's cool to at least compare the outputs.

**Review by martinhoyer — APPROVED** [review]

**Comment by happz** [comment]
> Nice, have you also tried [j2lint](https://github.com/aristanetworks/j2lint)?
> 
> ```
>   - repo: https://github.com/aristanetworks/j2lint.git
>     rev: v1.1.0
>     hooks:
>       - id: j2lint
>         args: [--ignore, 'jinja-statements-indentation', 'jinja-variable-lower-case', --]
> ```
> 
> Of course if the intention is to also have formatter, then it's a moot point, but I guess it's cool to at least compare the outputs.

I did not, I will, yes, I would like to use formatted as well, but I have not tried that one yet (too scared of all possible changes :) +1 to comparing results - maybe we end up using both :)

**Comment by happz** [comment]
@martinhoyer added j2lint in 508a1a74

**Comment by happz** [comment]
Unrelated failures, merging.

**Pull request merged**
