### PR TITLE
Print only failed objects when linting in hook

### PR DESCRIPTION
**Pull request by lukaszachy**
Success == silence, let's not be verbose and print only what we have to. 

Fix: #1819

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Comment by psss** [comment]
Seems that tests will need some adjustments as well:

```
:: [ 10:51:29 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.T8eRWUUO' should contain '/good' 
```

**Comment by lukaszachy** [comment]
> Seems that tests will need some adjustments as well:
> 
> ```
> :: [ 10:51:29 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.T8eRWUUO' should contain '/good' 
> ```

Done in https://github.com/teemtee/tmt/commit/7b7382b02b4c6f85b808dbf54ef62332cce686cd
If only github didn't have outage...

**Comment by lukaszachy** [comment]
Amended commit to change the hash and force pushed.

**Review by psss — APPROVED** [review]
Looks good, just two comments:

* When running `pre-commit run -a tmt-tests-lint` the failure is shown three times
* Would it make sense to include the `tmt-lint` check in `.pre-commit-config.yaml`?

**Comment by lukaszachy** [comment]
Solved via chat but placing here for future reference

> Looks good, just two comments:
> 
>     * When running `pre-commit run -a tmt-tests-lint` the failure is shown three times

There are 632 fmf files to be checked when `-a` is used and pre-commit splits that into more consumable chunks. 
It just happens that used test is defined in 3 files and each of them is used in separate command.

>     * Would it make sense to include the `tmt-lint` check in `.pre-commit-config.yaml`?

Definitely, but lets wait on the 1.23 release so it is less verbose on success :)

**Pull request merged**
