### PR TITLE
Remove prepare/install fields leaking into prepare step data

### PR DESCRIPTION
**Pull request by happz**
Pull Request Checklist

* [x] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Comment by skycastlelily** [comment]
I failed to find anything Not  perfect, so to prove that I do have review this MR carefully,I'd like to suggest: add a help message to [how](https://github.com/teemtee/tmt/blob/main/tmt/steps/__init__.py#L256 ) : The method name step uses ^^

**Review by skycastlelily — APPROVED** [review]

**Review by therazix — APPROVED** [review]

**Comment by psss** [comment]
Looks good, let's rebase and merge to unblock #2985?

**Comment by happz** [comment]
Unrelated failures, merging.

**Pull request merged**
