### PR TITLE
Add dnf support for rsync install

### PR DESCRIPTION
**Pull request by BeeGrech**
PR for issue #1051 

Add support for dnf package manager to install rsync on guest

### CODE REVIEW

**Comment by psss** [comment]
> Downside would be the removal of auto-healing (e.g. if rsync is removed by accident in the test). So if we value that (and expect to happen) then try/except would be better approach

This actually happens during the `installability` test of the `rsync` component and lead to the introduction of the `_check_rsync()` method. So I believe we need to cover this one anyway not to regress.

**Comment by BeeGrech** [comment]
> Thanks much for looking into this! Looks good in general. On the other hand I think we are already doing too many extra checks on the guest and this change is adding one more command before each `guest.push()` or `guest.pull()`.
> 
> I was thinking about improving this by trying `rsync` first and only if it fails checking the guest. It could look like this:
> 
> ```python
> try:
>     self.run(["rsync", ...])
> except tmt.utils.RunError:
>     try:
>         self._check_rsync()
>         self.run(["rsync", ...])
>     except tmt.utils.RunError:
>         self.fail(...)
> ```
> 
> @lukaszachy, @FrNecas what do you think?

Was trying to make it reusable as possible :)

I have the same thoughts as @lukaszachy said,

**Comment by psss** [comment]
We've discussed the approach below on the hacking session today:

```python
try:
    self.run(["rsync", ...])
except tmt.utils.RunError:
    try:
        self._check_rsync()
        self.run(["rsync", ...])
    except tmt.utils.RunError:
        self.fail(...)
```

The outcome was that this seems to be the best way how to address the issue for now. In the future we might enhance the final part of the `provision` step as well.

@BeeGrech, are you willing to adjust your changes based on this? The `_check_rsync()` method can nicely handle the new check for `dnf` versus `yum` as well.

**Comment by BeeGrech** [comment]
So just to confirm I am understanding correctly, modify the push and pull methods, with this Try Except clause, then fold the new pkg_mgr method into _check_rsync method?

**Comment by psss** [comment]
Yes, exactly. The method could start with a `rsync --version` check and bail out immediately if `rsync` is already installed (which would mean a real synchronization failure appeared) so that the original `error` could be re-reraised from `push()` or `pull()`.

**Comment by psss** [comment]
We've renamed the default branch to `main`. I've rebased on the latest `main` which should fix the problem.

**Review by psss — APPROVED** [review]
Thanks for the improvements. Looks good. Added just a few adjustments in a41f4b3.

**Pull request merged**
