### PR TITLE
Add the remote plan with polarion tests

### PR DESCRIPTION
**Pull request by jscotka**
Using remote tests for polarion testing: https://github.com/teemtee/tests/pull/1

### CODE REVIEW

**Comment by psss** [comment]
Fresh `tmt` is available in Testing Farm, let's see what happens now! I've disabled the inheritance to prevent inheriting the `execute` step definition.

**Comment by psss** [comment]
Most probably failed because of `tmt plan export` tracebacking on remote plans: #1729

**Comment by psss** [comment]
We'll be able to verify this once `tmt-1.20` with the fix for #1729 is deployed in the Testing Farm --> moving to `1.21`.

**Comment by psss** [comment]
Everything should be ready in the tooling, so let's try if it works ;-) Rebased on the latest `main` as well.

**Comment by psss** [comment]
Tests are failing:

* `/tests/core/dry` because of non-existing directory
* `/tests/discover/dynamic-ref/fmf` because of an outdated `fedora` branch in @jscotka fork
* `/requre/polarion` because of recent `logger` changes in #1685 

@kkaarreell, do you think the dynamic ref test could be updated not to rely on the fork branches?

**Comment by kkaarreell** [comment]
@psss Does it? I would say it uses the branch of the project itself.

**Comment by kkaarreell** [comment]
We could hardcode tmt repo

**Comment by psss** [comment]
> We could hardcode tmt repo

Sounds good.

**Comment by kkaarreell** [comment]
> > We could hardcode tmt repo
> 
> Sounds good.

maybe this would be it https://github.com/teemtee/tmt/pull/1810

**Comment by adiosnb** [comment]
> Tests are failing:
> 
>     * `/tests/core/dry` because of non-existing directory
> 
>     * `/tests/discover/dynamic-ref/fmf` because of an outdated `fedora` branch in @jscotka fork
> 
>     * `/requre/polarion` because of recent `logger` changes in [Decouple logging from objects and base classes #1685](https://github.com/teemtee/tmt/pull/1685)
> 
> 
> @kkaarreell, do you think the dynamic ref test could be updated not to rely on the fork branches?

I am trying to fix the test with `--dry` options with this https://github.com/teemtee/tmt/pull/1811. What do you think?

**Comment by adiosnb** [comment]
@jscotka If tests in https://github.com/teemtee/tmt/pull/1811 are OK, please merge https://github.com/jscotka/tmt/pull/1 into this PR. Or we can discuss the next steps.

**Comment by psss** [comment]
@kkaarreell, @adiosnb, thank you both for the fixes. I suggest to merge #1811 to `main` when tests are green and rebase this pull request on it.

**Comment by psss** [comment]
Adding `logger` to the remote tests in teemtee/tests/pull/2.

**Comment by jscotka** [comment]
results of remote plan seems well,

**Comment by lukaszachy** [comment]
Polarion tests will need update after #1937 is merged, right?

**Comment by KwisatzHaderach** [comment]
Don't think so, there is one tests right now (tests/report/polarion), which is only in tmt repo and is disabled for obvious reasons.
What really needs to be done is moving the test to the tests repo and enabling it, definitely not worth doing here.

**Comment by jscotka** [comment]
@psss I though that dry run issue is already fixed, seems not. reased and it still failed.

**Comment by psss** [comment]
Yes, one issue related to `--dry` has been fixed in 372a5d25. This looks like another one. @adiosnb, could you possibly have a look?

**Comment by adiosnb** [comment]
> Yes, one issue related to `--dry` has been fixed in [372a5d2](https://github.com/teemtee/tmt/commit/372a5d25a27abd15098472db9e71a09b3f2b32fb). This looks like another one. @adiosnb, could you possibly have a look?

Hi, I've changed the position of  `--dry` option from the virtual step to global, and it fixed the test. The problem was that do `my_run` did not see the `dry` option set to `True` and tried to clone a remote plan into an uninitialized directory structure.

Old: `tmt run --all --remove provision --how virtual --dry`
New: `tmt run --dry --all --remove provision --how virtual`

@psss @jscotka What do you think about modifying the test in this way?

**Review by psss — APPROVED** [review]
Thanks for preparing the remote `polarion` tests. I've fixed the problem with the `provision --dry` traceback for imported plans in 47b9250f. Now all tests seem to be green.

**Pull request merged**
