### PR TITLE
Fix normalization of `hardware` key/option

### PR DESCRIPTION
**Pull request by happz**
A bug was introduced in the patching adding multiple disks to testcloud plugin, and the test was missing.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Comment by happz** [comment]
@martinhoyer to my horror, I broke `hardware` normalization, and since I didn't bother to add a unit test, nobody noticed till I used `--hardware` just this evening. So, I suppose one more to include in 1.34, this time it's a genuine bug fix :/

**Comment by martinhoyer** [comment]
Nice catch. Thanks for the heads-up.  
I'd say we can do the release on Monday anyway. (DevConf)  
Unless you really want to do this week :)

**Review by martinhoyer — COMMENTED** [review]
It looks good to me, but clearly I don't understand the code enough to be able to click approve with clear conscience.  
@happz If you could help me understand, it would be much appreciated :pray:  
I get that line 519 is `merged[components.name] = []` as there is peer_index, but am not sure why `merged[components.name]` is otherwise `{}`. Am I looking correctly at https://github.com/teemtee/tmt/blob/e4991dd46c765151a1280f9e0f89ce3ebf38202e/tmt/hardware.py#L230 ?

**Comment by martinhoyer** [comment]
@psss @lukaszachy Could you take a look please, so we can do the release? :)

**Comment by lukaszachy** [comment]
Hm, there is missing fmf on rawhide (as it cannot be built https://kojipkgs.fedoraproject.org//work/tasks/6207/118796207/build.log) which blocks tmt.

**Comment by martinhoyer** [comment]
> Hm, there is missing fmf on rawhide (as it cannot be built https://kojipkgs.fedoraproject.org//work/tasks/6207/118796207/build.log) which blocks tmt.
> 
> Hm, we should monitor bugzilla as well, it was opened in May :/ (https://bugzilla.redhat.com/show_bug.cgi?id=2279994)

whoops. I wonder if https://github.com/teemtee/fmf/issues/194 has something to do with it.  
Probably shouldn't block this PR though?

**Comment by martinhoyer** [comment]
> whoops. I wonder if [teemtee/fmf#194](https://github.com/teemtee/fmf/issues/194) has something to do with it. Probably shouldn't block this PR though?

actually, I think it's the use of pkg_resources. Looking into it.

**Comment by happz** [comment]
> It looks good to me, but clearly I don't understand the code enough to be able to click approve with clear conscience. @happz If you could help me understand, it would be much appreciated 🙏 I get that line 519 is `merged[components.name] = []` as there is peer_index, but am not sure why `merged[components.name]` is otherwise `{}`. Am I looking correctly at
> 
> https://github.com/teemtee/tmt/blob/e4991dd46c765151a1280f9e0f89ce3ebf38202e/tmt/hardware.py#L230
> 
> ?

`merged` is basically this structure:

```yaml
merged:
  # merged[component.name] = [] for these:
  disk:
    - size: 10GB
    - size: 10GB
  network:
    - type: eth

  # merged[component.name] = {} for these:
  cpu:
    flags:
      - avs
      - avs2
    model: 79
  device:
    vendor: ...

  # and merged[component.name] is whatever the value is for these:
  hostname: foo.bar.com
  memory: 4GB
```

The issue was in `merged[components.name] = []` being used for all three kinds of requirements.

**Review by martinhoyer — APPROVED** [review]
Thanks @happz, much appreciated!

**Review by lukaszachy — APPROVED** [review]

**Pull request merged**
