### PR TITLE
Fix polarion report pruning and add or fix arguments

### LINKED ISSUE #1910: tmt better Polarion testrun report support
1. In https://tmt.readthedocs.io/en/stable/spec/plans.html#polarion,  testrun-title field value actually match to testrun-id in Polarion. This is wrong and needs fixing badly.  

In Polarion. testrun-id is generated automatically with a time stamp format, testrun-title is message with meaningful information.

Now tmt automatically uploads a testrun with empty testrun title.

 

2. support setting Poalrion testrun plannedin field: matches to poalrion xunit importer property: polarion-custom-plannedin

 

3. support setting  Poalrion testrun assignee field: matches to poalrion xunit importer property: polarion-custom-assignee

4. support setting  Poalrion testrun subsystem field: matches to poalrion xunit importer property: polarion-custom-poolteam

### PR DESCRIPTION
**Pull request by KwisatzHaderach**
Change testrun-title to title and fix incorrect usage as id
Add arguments for planned-in, assignee, pool-team, arch, platform, build, sample-image, logs and composeid custom fields
Don't prune xunit file

fixes #1910

### CODE REVIEW

**Comment by jencce** [comment]
> 

Hi, Thanks for fixing this!

I got this in my test out:
```
    report
    workdir: /var/tmp/tmt/run-005/plans/local/report
        how: polarion
    finish
    workdir: /var/tmp/tmt/run-005/plans/local/finish
        Doing nothing to stop guest 'localhost'.
        Doing nothing to remove guest 'localhost'.
        summary: 0 tasks completed
Traceback (most recent call last):
  File "/usr/bin/tmt", line 62, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1030, in _process_result
    **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tmt/cli.py", line 357, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 2703, in go
    plan.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1659, in go
    step.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/report/__init__.py", line 105, in go
    cast(Union[Action, ReportPlugin], phase).go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/report/polarion.py", line 115, in go
    import_polarion()
  File "/usr/lib/python3.6/site-packages/tmt/export/polarion.py", line 39, in import_polarion
    from pylero.work_item import TestCase as PolarionTestCase
  File "/usr/lib/python3.6/site-packages/pylero/work_item.py", line 1582, in <module>
    vals = bp.get_valid_field_values("workitem-type")
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 1046, in get_valid_field_values
    project_id = getattr(self, "project_id", None) or self.default_project
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 30, in __get__
    return classmethod(self.fget).__get__(instance, cls)()
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 311, in default_project
    cls.session
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 30, in __get__
    return classmethod(self.fget).__get__(instance, cls)()
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 298, in session
    BasePolarion._session = Connection.session()
  File "/usr/lib/python3.6/site-packages/pylero/base_polarion.py", line 177, in session
    cls.session._login()
  File "/usr/lib/python3.6/site-packages/pylero/session.py", line 138, in _login
    id_element = sc.last_received().childAtPath("Envelope/Header/sessionID")
  File "/usr/lib/python3.6/site-packages/pylero/session.py", line 234, in __getattr__
    return getattr(self._suds_client, attr)
AttributeError: 'Client' object has no attribute 'last_received'
```

No report xunit.xml generated.
```
# ls /var/tmp/tmt/run-005/plans/local/report
default-0  step.yaml
# ls /var/tmp/tmt/run-005/plans/local/report/default-0/
# ls
plans  stories  tools
# cat plans/local.fmf
......snipped......
execute:
    how: tmt
    framework: shell
report:
    how: polarion
    file: xunit.xml
    project-id: XXXXL
    title: local debug plan
    upload: False
#
# rpm -qa | grep tmt
tmt-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-provision-container-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-report-polarion-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-provision-virtual-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
python3-tmt-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-report-reportportal-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-all-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-report-html-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-report-junit-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch
tmt-test-convert-1.22.dev-1.20230323110924174542.pr1937.50.g5b66d3d.el8.noarch

```

**Comment by KwisatzHaderach** [comment]
@jencce Haven't hit this one yet so not sure what is the cause (I tried multiple ways to fail). Please make sure you are using the latest (0.0.8) pylero and either a machine account or your own user with personal access token (upload won't work with token authentication).

**Comment by jencce** [comment]
> @jencce Haven't hit this one yet so not sure what is the cause (I tried multiple ways to fail). Please make sure you are using the latest (0.0.8) pylero and either a machine account or your own user with personal access token (upload won't work with token authentication).

It is 0.0.8 pylero.
With machine account I got this message. With personal account, says my passwd is invalid. Polarion is authenticated via SSO, personal account can't even login.
However I put upload to False, why login with pylero is still needed?

**Comment by KwisatzHaderach** [comment]
Password is no longer working for personal accounts (for the past couple weeks), you have to use personal access token.
Login to polarion is needed to get info about the cases that you executed, so it's expected that they can be matched, meaning have an id in fmf file and have the same id in relevant polarion case.
However this is failing on import of TestCase class from pylero, which means login issue, it didn't even get to matching the test cases. With machine account it should have no problem as long as you have user and password in the config file or env vars.

maybe @leelavg from pylero project can help here?

**Comment by jencce** [comment]
> Password is no longer working for personal accounts (for the past couple weeks), you have to use personal access token. Login to polarion is needed to get info about the cases that you executed, so it's expected that they can be matched, meaning have an id in fmf file and have the same id in relevant polarion case. However this is failing on import of TestCase class from pylero, which means login issue, it didn't even get to matching the test cases. With machine account it should have no problem as long as you have user and password in the config file or env vars.
> 
> maybe @leelavg from pylero project can help here?

Got it. Thanks for the info!

Turns out I missed some dependencies in pip and need to restart pipenv.
I got the xunit file generated but no title, planned-in, and sst name in the xunit.xml.

tail of xunit.xml:
```
<properties>
<property name="polarion-project-id" value="RHELKERNEL" />
<property name="polarion-user-id" value="kernel_machine" />
<property name="polarion-testrun-id" value="local20230324085407" />
<property name="polarion-project-span-ids" value="RHELKERNEL" />
</properties></testsuites>
```
part of plan.fmf:
```
report:
    how: polarion
    file: xunit.xml
    project-id: RHELKERNEL
    title: local debug plan
    planned-in: fedora-32
    pool-team: alpha
    upload: False
```

**Comment by KwisatzHaderach** [comment]
From that output I see you don't have this PR with locally built tmt, but rather just using tmt from repos as this PR is not yet merged the code is not there yet :)

you should be able to clone this repo, checkout polarion_report_fixes branch and run `sudo ./setup.py install` in tmt base folder, that should add the tmt from sources as primary tmt, after that you can try this out

we are actually waiting with the merge for your approval or any additional requests (on this topic), I added more arguments than you requested because those will be useful for my project so I might as well add others if they would be required

**Comment by KwisatzHaderach** [comment]
@jencce Actually I just noticed you have the packages as per Lukas's comment, maybe you have more versions of tmt locally? Because this clearly looks like a clean tmt without this patch...you can of course install from git repo as well.

**Comment by waynesun09** [comment]
@leelavg The error with `last_received` is fixed with upstream suds, but with RHEL8 still on `suds-jurko` which have removed that function which I have requested backport with:

https://bugzilla.redhat.com/show_bug.cgi?id=2106152

@jencce @KwisatzHaderach due to the `python-suds` bug, the pylero package installed with yum using the python-suds (suds-jurko) on EL8 will have the issue, while it works with pip install pylero from upstream release.

**Comment by jencce** [comment]
> From that output I see you don't have this PR with locally built tmt, but rather just using tmt from repos as this PR is not yet merged the code is not there yet :)
> 
> you should be able to clone this repo, checkout polarion_report_fixes branch and run `sudo ./setup.py install` in tmt base folder, that should add the tmt from sources as primary tmt, after that you can try this out
> 
> we are actually waiting with the merge for your approval or any additional requests (on this topic), I added more arguments than you requested because those will be useful for my project so I might as well add others if they would be required

Like your later comment, I did installed packages with the patch. For a clear test env, I run those tests in a scratch new provison EL8. I'll check again the next week with installing from git repo, and check what's other needs per Polarion testrun's requirements.

Thanks very much for all the effort! I really appreciate it!

**Comment by jencce** [comment]
> * Seems I got pinged here, didn't went through all the conversation
> 
>     * The error ` last_received` caught my attention, suds dep had this issue and @waynesun09 got this fixed upstream
> 
>     * Maybe some incorrect suds version was installed in your env, could you pls mention your machine info `/etc/system-release-cpe`?
> 
> 
> Pls expect a delayed response.
```
# cat /etc/system-release-cpe
cpe:/o:redhat:enterprise_linux:8::baseos
```

Thanks for looking into it! I'll try to install pylero from upstream.

**Comment by jencce** [comment]
> > From that output I see you don't have this PR with locally built tmt, but rather just using tmt from repos as this PR is not yet merged the code is not there yet :)
> > you should be able to clone this repo, checkout polarion_report_fixes branch and run `sudo ./setup.py install` in tmt base folder, that should add the tmt from sources as primary tmt, after that you can try this out
> > we are actually waiting with the merge for your approval or any additional requests (on this topic), I added more arguments than you requested because those will be useful for my project so I might as well add others if they would be required
> 
> Like your later comment, I did installed packages with the patch. For a clear test env, I run those tests in a scratch new provison EL8. I'll check again the next week with installing from git repo, and check what's other needs per Polarion testrun's requirements.
> 
> Thanks very much for all the effort! I really appreciate it!
Install from repo , python3 ./setup.py install hits error:
```
Processing rpds_py-0.7.1.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-rqv823ep/rpds_py-0.7.1.tar.gz
[root@hp-dl388g8-20 tmt]# git branch -vv
  main 0e9014d [origin/main] Run `chcon` only if SELinux fs supported
* pol  5b66d3d [origin/polarion_report_fixes] Fix polarion report pruning and add or fix arguments
[root@hp-dl388g8-20 tmt]#
```

**Comment by jencce** [comment]
> > * Seems I got pinged here, didn't went through all the conversation
> >   
> >   * The error ` last_received` caught my attention, suds dep had this issue and @waynesun09 got this fixed upstream
> >   * Maybe some incorrect suds version was installed in your env, could you pls mention your machine info `/etc/system-release-cpe`?
> > 
> > Pls expect a delayed response.
> 
> ```
> # cat /etc/system-release-cpe
> cpe:/o:redhat:enterprise_linux:8::baseos
> ```
> 
> Thanks for looking into it! I'll try to install pylero from upstream.

Failed to install from pylero repo:

```
[root@hp-dl388g8-20 pylero]# git branch
* main
[root@hp-dl388g8-20 pylero]# git remote
origin
[root@hp-dl388g8-20 pylero]# pip3 install .
Traceback (most recent call last):
  File "/usr/bin/pip3", line 7, in <module>
    from pip import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 42, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
[root@hp-dl388g8-20 pylero]#
```

**Comment by jencce** [comment]
After checking, except fields in the description, we also need custom fields: "composeid"  and "logs". Thanks!

**Comment by jencce** [comment]
> > > From that output I see you don't have this PR with locally built tmt, but rather just using tmt from repos as this PR is not yet merged the code is not there yet :)
> > > you should be able to clone this repo, checkout polarion_report_fixes branch and run `sudo ./setup.py install` in tmt base folder, that should add the tmt from sources as primary tmt, after that you can try this out
> > > we are actually waiting with the merge for your approval or any additional requests (on this topic), I added more arguments than you requested because those will be useful for my project so I might as well add others if they would be required
> > 
> > 
> > Like your later comment, I did installed packages with the patch. For a clear test env, I run those tests in a scratch new provison EL8. I'll check again the next week with installing from git repo, and check what's other needs per Polarion testrun's requirements.
> > Thanks very much for all the effort! I really appreciate it!
> > Install from repo , python3 ./setup.py install hits error:
> 
> ```
> Processing rpds_py-0.7.1.tar.gz
> error: Couldn't find a setup script in /tmp/easy_install-rqv823ep/rpds_py-0.7.1.tar.gz
> [root@hp-dl388g8-20 tmt]# git branch -vv
>   main 0e9014d [origin/main] Run `chcon` only if SELinux fs supported
> * pol  5b66d3d [origin/polarion_report_fixes] Fix polarion report pruning and add or fix arguments
> [root@hp-dl388g8-20 tmt]#
> ```

This is gone after using python-3.9

**Comment by leelavg** [comment]
anything required from pylero side? or else I'll be unsubscribing from this issue.

**Comment by jencce** [comment]
> anything required from pylero side? or else I'll be unsubscribing from this issue.

There is no error after installed upstream pylero. I guess you're safe to unsubscribe. Sorry for all the noise I made. :)

**Comment by jencce** [comment]
By installing from the branch origin/polarion_report_fixes, all intended fields are generated. With some modification it can be submitted to polarion. 

Thanks very much!  Sorry for the late.

A tip, to install tmt from source repo, this is needed first:
```
pip3.9 install junit_xml
```

**Comment by KwisatzHaderach** [comment]
Right, yeah I tried with RHEL8 yesterday and just gave up when I realised it will not work with packaged pylero/suds for python 3.6. Thanks for testing it, what modifications are you making? it should be uploadable to polarion without any changes...at least to the 2 projects I tried.

For adding composeid and logs, sure, I'll add it.

**Review by lukaszachy — APPROVED** [review]

**Pull request merged**
