### PR TITLE
Replace spaces with underscores if making workdir

### PR DESCRIPTION
**Pull request by idorax**
fix: #1520

### CODE REVIEW

**Comment by idorax** [comment]
With the patch, I manually tested it, the test result looks good.
```bash
(tmt) huanli@kvm-01-guest02:foo$ (cd ../dev; git show)
...<snip>...
diff --git a/tmt/utils.py b/tmt/utils.py
index 6aac821..1671048 100644
--- a/tmt/utils.py
+++ b/tmt/utils.py
@@ -765,8 +765,10 @@ class Common:
         # Need the parent workdir
         if self.parent is None or self.parent.workdir is None:
             return None
-        # Join parent name with self
-        return os.path.join(self.parent.workdir, self.name.lstrip('/'))
+        # Join parent name with self. Note spaces in the base name are replaced with underscores
+        # on purpose because it is not user friendly if a directory path contains spaces
+        base_name = re.sub(r'\s+', '_', self.name).lstrip('/')
+        return os.path.join(self.parent.workdir, base_name)
 
     def _workdir_load(self, workdir: WorkdirArgumentType) -> None:
         """
(tmt) huanli@kvm-01-guest02:foo$ cat plans/foo.fmf 
summary: Basic smoke test
discover:
    name: A B C D e f g 
    how: fmf
execute:
    how: tmt
(tmt) huanli@kvm-01-guest02:foo$ tmt -d run discover
/var/tmp/tmt/run-001

/plans/foo
    Report step always force mode enabled.
    discover
    workdir: /var/tmp/tmt/run-001/plans/foo/discover
        how: fmf
        name: A B C D e f g
        Git root not found, using '/home/huanli/dev/1520/foo.'
        directory: /home/huanli/dev/1520/foo
        Copy '/home/huanli/dev/1520/foo' to '/var/tmp/tmt/run-001/plans/foo/discover/A_B_C_D_e_f_g/tests'.
        Check metadata tree in '/var/tmp/tmt/run-001/plans/foo/discover/A_B_C_D_e_f_g/tests/'.
        summary: 1 test selected
# ^^^^^ name: A B C D e f g
# ^^^^^ directory path: /var/tmp/tmt/run-001/plans/foo/discover/A_B_C_D_e_f_g/tests
```

Hi @psss, do we need to add one simple test to cover this fix?

**Review by psss — APPROVED** [review]
Thanks for preparing the fix. Looks good in general. I propose a couple of adjustments in 959181f6:

 * substitute all special characters (and strip them from the begining/end)
 * use dash to keep consistency with other naming (default step names, run names, key names)
 * and use `safe_name` as the usage is not limited to filesystem paths only

@idorax, @happz, are you ok with the changes?

**Comment by happz** [comment]
Fine with me except line 271 - I don’t understand why ‘safe_name’ is used for ‘prefix’. Prefix is then used with ‘test.name’ which may contain its own pile of unsafe characters, invalidating the effort. I’d keep using ‘phase.name’ since it’s used for *name* anyway, no harm in name containing spaces, is it?

**Comment by psss** [comment]
I've updated the `prefix` to contain the safe name in order to prevent introducing unsafe characters to safe test names: If all tests in the git repository have nice & safe names, the prefix could still introduce unsafe characters from the `discover` step name.

**Comment by psss** [comment]
In order to make it more clear, here's an example:

```yaml
discover:
  - name: more words
    how: fmf
  - name: something @#$% ugly?!
    how: fmf
execute:
    how: tmt
```

Without safe `prefix` we get this:

```
> tmt run discover -v
/var/tmp/tmt/run-046

/plans/simple
    discover
        how: fmf
        name: more words
        directory: /tmp/safe
        how: fmf
        name: something @#$% ugly?!
        directory: /tmp/safe
        summary: 6 tests selected
            /more words/tests/one
            /more words/tests/three
            /more words/tests/two
            /something @#$% ugly?!/tests/one
            /something @#$% ugly?!/tests/three
            /something @#$% ugly?!/tests/two
```

With the safe `prefix` the test names are nice again:

```
> tmt run discover -v
/var/tmp/tmt/run-045

/plans/simple
    discover
        how: fmf
        name: more words
        directory: /tmp/safe
        how: fmf
        name: something @#$% ugly?!
        directory: /tmp/safe
        summary: 6 tests selected
            /more-words/tests/one
            /more-words/tests/three
            /more-words/tests/two
            /something-ugly/tests/one
            /something-ugly/tests/three
            /something-ugly/tests/two
```

**Comment by idorax** [comment]
> I would argue the first example is exactly what tmt should print out.

\+ 1, @psss, right here I'm with @happz because if user prefers special characters in names, it's straightforward to show the original special characters.  If there is any problem, user should be responsible for correcting the special characters. For tmt, it just need to make sure the names stored in filesystems.   That is, I'm with this one:

```
> tmt run discover -v
/var/tmp/tmt/run-046

/plans/simple
    discover
        how: fmf
        name: more words
        directory: /tmp/safe
        how: fmf
        name: something @#$% ugly?!
        directory: /tmp/safe
        summary: 6 tests selected
            /more words/tests/one
            /more words/tests/three
            /more words/tests/two
            /something @#$% ugly?!/tests/one
            /something @#$% ugly?!/tests/three
            /something @#$% ugly?!/tests/two
```

**Comment by psss** [comment]
> I would argue the first example is **exactly** what `tmt` should print out. There is no `discover` step named `more-words`, as can be seen clearly in the fmf source: `name: more words`. There's no dash in the step name. Filesystem paths are implementation detail, it's up to `tmt` to decide how and where to store data, on the other hand, step, story, and test names are all given by users and should be reported as such.

> @psss, right here I'm with @happz because if user prefers special characters in names, it's straightforward to show the original special characters. If there is any problem, user should be responsible for correcting the special characters. For tmt, it just need to make sure the names stored in filesystems safely and user friendly as well. That is, I'm with this one:

Good points! Makes sense. Thanks for the review and explanation! I've reverted the test name change back and rebased.

**Pull request merged**
