### PR TITLE
Improve structure of the packit config a bit

### PR DESCRIPTION
**Pull request by psss**
* Add comments describing jobs.
* Use consistent indentation.

### CODE REVIEW

**Comment by happz** [comment]
How about employing a YAML formatter, e.g. one running in pre-commit time like https://github.com/jumanjihouse/pre-commit-hook-yamlfmt? There are 60 files with `.yaml` suffix, 10 `.yml`, and 646 `.fmf` files in the tmt repository, keeping consistent formatting might be a futile effort for humans. We can start slow as always, gradually cover directories until the whole repo is "protected".

**Comment by psss** [comment]
> How about employing a YAML formatter, e.g. one running in pre-commit time...

Nice idea!

**Review by lukaszachy — APPROVED** [review]

**Pull request merged**
