### PR TITLE
Support `beaker.pool` hardware requirement for mrack

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature
* [ ] write the documentation
* [x] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Review by therazix — APPROVED** [review]
LGTM. Tests should pass after https://github.com/teemtee/tmt/pull/3058 is merged.

**Review by thrix — APPROVED** [review]
LGTM

**Comment by happz** [comment]
Unrelated failures, merging.

**Pull request merged**
