### PR TITLE
Bootstrap unit tests for Beaker XML transformation of HW requirements

### PR DESCRIPTION
**Pull request by happz**
Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Comment by happz** [comment]
> Looks good, thanks!

@psss if possible, I'd recommend merging https://github.com/teemtee/tmt/pull/2596/ first, it adds the directories this PR builds on.

**Comment by psss** [comment]
> @psss if possible, I'd recommend merging #2596 first, it adds the directories this PR builds on.

Ack, I've just reviewed it.

**Comment by psss** [comment]
@happz, could you please review the conflict which appeared after the `tpm` pull request rebase? Thanks.

**Comment by happz** [comment]
> @happz, could you please review the conflict which appeared after the `tpm` pull request rebase? Thanks.

I'll wait for https://github.com/teemtee/tmt/pull/2596 to get in - I tried to rebase, but all those "squash" commits are making a mess out of it :/

**Comment by psss** [comment]
> I'll wait for #2596 to get in - I tried to rebase, but all those "squash" commits are making a mess out of it :/

Sure, understand.

**Comment by happz** [comment]
> > I'll wait for #2596 to get in - I tried to rebase, but all those "squash" commits are making a mess out of it :/
> 
> Sure, understand.

Rebased.

**Pull request merged**
