### PR TITLE
Fix incorrect translation of `cpu.processors` to Beaker

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Comment by happz** [comment]
@skycastlelily I'd suggest being more specific in your commit message. "Fix a typo" does not help a potential reader, on the other hand, "Fix incorrect translation of cpu.processors to Beaker" would provide much more context.

**Comment by skycastlelily** [comment]
> @skycastlelily I'd suggest being more specific in your commit message. "Fix a typo" does not help a potential reader, on the other hand, something like "Fix incorrect translation of cpu.processors to Beaker" would provide much more context.

Thanks, and updated^^

**Review by happz — APPROVED** [review]

**Review by psss — APPROVED** [review]

**Pull request merged**
