### PR TITLE
Don't run `ShellCheck` on tests & decrease severity

### PR DESCRIPTION
**Pull request by jamacku**
follow-up to:
- #1959
- #1974

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Review by janhavlin — APPROVED** [review]

**Review by psss — APPROVED** [review]
Thanks for prioritizing the `exclude-path` feature and for providing the config! Looks good. I've just squashed the commits and adjusted the summary to match the [recommendations](https://tmt.readthedocs.io/en/latest/contribute.html#commits).

**Pull request merged**
