### PR TITLE
Support `system.numanodes` hardware requirement for mrack

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature
* [ ] write the documentation
* [x] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Comment by happz** [comment]
@skycastlelily when you have some spare time, rebase on top of the recent `main`, please, and resolve conflicts.

**Comment by skycastlelily** [comment]
Updated^^

**Review by happz — APPROVED** [review]

**Review by therazix — APPROVED** [review]

**Comment by happz** [comment]
Plenty of timeout issues, seems like Internet is lazy today. Does not seem related to HW requirement parsing.

**Pull request merged**
