### PR TITLE
Disallow Guest.push if guest is unavailable

### PR DESCRIPTION
**Pull request by idorax**
fix: #983

### CODE REVIEW

**Comment by idorax** [comment]
With the fix, `tmt run -a login` looks like:
```bash
(tmt) huanli@kvm-01-guest02:plans$ cat foo.fmf 
execute:
    how: tmt
test: echo
discover:
    how: fmf
provision:
    how: virtual
    image: FOOOOOOOOOOOOOOOOOO
(tmt) huanli@kvm-01-guest02:plans$ tmt run -a login
/var/tmp/tmt/run-003

/plans/foo
    discover
        how: fmf
        directory: /home/huanli/dev/983/foo-bad
        summary: 1 test selected
    provision
        how: virtual
        user: root
        key: []
        image: FOOOOOOOOOOOOOOOOOO
        memory: 2048 MB
        disk: 10 GB
        arch: x86_64
    finish
        login: Starting interactive shell
        warn: Failed to push workdir to the guest.
The guest is not available.
```

**Comment by idorax** [comment]
@lukaszachy, would you please help to review this PR? Thanks!

**Comment by idorax** [comment]
In https://artifacts.dev.testing-farm.io/573446c5-f255-41eb-8bd0-44a195cef956/, test `/tests/precommit` failed. e.g.
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   Hook: tmt-tests-lint
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [ 11:13:27 ] :: [  BEGIN   ] :: Creating tmp directory :: actually running 'tmp=$(mktemp -d)'
:: [ 11:13:27 ] :: [   PASS   ] :: Creating tmp directory (Expected 0, got 0)
/tmp/tmp.uWjMJ77RMt /var/ARTIFACTS/work-advancedOIDz3J/plans/features/advanced/discover/default/tests/tests/precommit
:: [ 11:13:27 ] :: [  BEGIN   ] :: Running 'pushd /tmp/tmp.uWjMJ77RMt'
:: [ 11:13:27 ] :: [   PASS   ] :: Command 'pushd /tmp/tmp.uWjMJ77RMt' (Expected 0, got 0)
:: [ 11:13:27 ] :: [  BEGIN   ] :: Running 'tmt init'
Tree '/tmp/tmp.uWjMJ77RMt' initialized.
To populate it with example content, use --template with mini, base or full.
:: [ 11:13:27 ] :: [   PASS   ] :: Command 'tmt init' (Expected 0, got 0)
:: [ 11:13:27 ] :: [  BEGIN   ] :: Running 'git init'
Initialized empty Git repository in /tmp/tmp.uWjMJ77RMt/.git/
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: git branch -m <name>
:: [ 11:13:28 ] :: [   PASS   ] :: Command 'git init' (Expected 0, got 0)
:: [ 11:13:28 ] :: [  BEGIN   ] :: Running 'git config --local user.name LZachar'
:: [ 11:13:28 ] :: [   PASS   ] :: Command 'git config --local user.name LZachar' (Expected 0, got 0)
:: [ 11:13:28 ] :: [  BEGIN   ] :: Running 'git config --local user.email lzachar@redhat.com'
:: [ 11:13:28 ] :: [   PASS   ] :: Command 'git config --local user.email lzachar@redhat.com' (Expected 0, got 0)
:: [ 11:13:28 ] :: [  BEGIN   ] :: Running 'cat .pre-commit-config.yaml'
repos:
  - repo: /var/ARTIFACTS/work-advancedOIDz3J/plans/features/advanced/discover/default/tests/tests/precommit/../..
    rev: "3dfa12e"
    hooks:
    - id: "tmt-tests-lint"
:: [ 11:13:28 ] :: [   PASS   ] :: Command 'cat .pre-commit-config.yaml' (Expected 0, got 0)
:: [ 11:13:28 ] :: [  BEGIN   ] :: Running 'pre-commit install'
/usr/share/beakerlib/testing.sh: line 878: pre-commit: command not found
:: [ 11:13:28 ] :: [   FAIL   ] :: Command 'pre-commit install' (Expected 0, got 127)
....<snip>...
```

@lukaszachy, any idea/suggestion?

**Comment by lukaszachy** [comment]
@idorax rebase to the current main, it was fixed in #1401 (and apologies for that breakage)

**Comment by idorax** [comment]
> @idorax rebase to the current main, it was fixed in #1401 (and apologies for that breakage)

Rebase is done. @lukaszachy, please help to review the commit, thanks!

**Review by lukaszachy — APPROVED** [review]
LGTM, thank you for the PR.

**Pull request merged**
