### PR TITLE
Copy the whole git repo only if necessary

### PR DESCRIPTION
**Pull request by FrNecas**
(creating as draft for now until I see that it doesn't break anything else)

Previously, the git repo was always copied during discover -h fmf, however
we only need the .git present only if some operations with git are
performed (e.g. checkout to a ref). Otherwise, the fmf root is
sufficient to enable tests to run. This preserves space/bandwith if
fmf root is different from git root.

Fixes: #1016

### CODE REVIEW

**Comment by lukaszachy** [comment]
I'd prefer explicit flag / option. One _might_ want to copy git even if they are not using ref/modified-....

**Comment by psss** [comment]
Agreed. Having an explicit option to always sync the whole git could possibly be useful. By default I'd suggest to save space.

**Comment by FrNecas** [comment]
Added one more missing option which requires git (fmf-id) + added the option to force the repo sync. Hopefully, tests should be green.

**Review by psss — APPROVED** [review]
Thanks for fixing this! Looks good. Added just a few minor adjustments in cac9de0.

**Comment by psss** [comment]
One hundred green tests! :champagne:

**Pull request merged**
