### PR TITLE
Test `result` key should be implemented as enum, not a string

### PR DESCRIPTION
**Pull request by happz**
This is a leftover from transitioning to enums in the past.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by martinhoyer — APPROVED** [review]

**Review by seberm — APPROVED** [review]

**Review by psss — APPROVED** [review]
Thanks for cleaning this up!

**Comment by psss** [comment]
Seems we have a little regression:

```
:: [ 08:12:17 ] :: [  BEGIN   ] :: Running 'tmt tests show mini'
/tests/mini
                    test ./test.sh
                    path /tests
               framework shell
                  manual false
                     tty false
                duration 5m
                 enabled true
                  result ResultInterpret.RESPECT
       restart_max_count 1
     restart_with_reboot false

:: [ 08:12:18 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.H4A4Jrdi' should contain 'result respect' 
```

**Comment by happz** [comment]
> Seems we have a little regression:
> 
> ```
> :: [ 08:12:17 ] :: [  BEGIN   ] :: Running 'tmt tests show mini'
> /tests/mini
>                     test ./test.sh
>                     path /tests
>                framework shell
>                   manual false
>                      tty false
>                 duration 5m
>                  enabled true
>                   result ResultInterpret.RESPECT
>        restart_max_count 1
>      restart_with_reboot false
> 
> :: [ 08:12:18 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.H4A4Jrdi' should contain 'result respect' 
> ```

Addressed in bad555bd

**Comment by psss** [comment]
Failing test is an unrelated `Unrecognized package manager.` error, merging.

**Pull request merged**
