### PR TITLE
Add support for emulated TPM into virtual provision plugin

### PR DESCRIPTION
**Pull request by happz**
Based on code introduced in https://github.com/teemtee/tmt/pull/2078, but honoring HW requirements.

Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [x] extend the test coverage
* [x] update the specification
* [x] mention the version
* [x] include a release note

### CODE REVIEW

**Comment by happz** [comment]
@frantisekz FYI, getting back to what you started in https://github.com/teemtee/tmt/pull/2078. TPM seems to be easy enough - I'll also include a test, I have no idea whether this works or not, yet.

**Comment by frantisekz** [comment]
tpm 1.2 is now supported too : https://pagure.io/testcloud/c/89f1c024ca829543de7f74f89329158c6dee3d83?branch=master

You can pass version str to the TPMConfiguration() object, libvirt supports 1.2 or 2.0 (default).

Ping me please when you'd need a new testcloud release with this.

**Comment by happz** [comment]
> tpm 1.2 is now supported too : https://pagure.io/testcloud/c/89f1c024ca829543de7f74f89329158c6dee3d83?branch=master
> 
> You can pass version str to the TPMConfiguration() object, libvirt supports 1.2 or 2.0 (default).
> 
> Ping me please when you'd need a new testcloud release with this.

Sorry, I missed your comment.

Yes, it would be nice to have a testcloud release with this feature. I'm closing on adding a test for it in tmt, this PR should be ready for reviews Soon(TM).

**Comment by frantisekz** [comment]
> Sorry, I missed your comment.
> 
> Yes, it would be nice to have a testcloud release with this feature. I'm closing on adding a test for it in tmt, this PR should be ready for reviews Soon(TM).

Okey dokey, I'll try to sprint in to have the next release tagged by around friday, I have bunch of wip stuff near the finish line that I'd like to include in.

**Comment by frantisekz** [comment]
testcloud-0.9.11 was released, TPMConfiguration objects now accept version parameter ("1.2" or "2.0" which are the only ones supported by libvirt).

**Comment by happz** [comment]
> testcloud-0.9.11 was released, TPMConfiguration objects now accept version parameter ("1.2" or "2.0" which are the only ones supported by libvirt).

Lovely, thank you! Tested both with testcloud-0.9.10 and testcloud-0.9.12, works perfectly.

**Review by psss — APPROVED** [review]
Nice! Thanks for implementing this.

**Pull request merged**
