### PR TITLE
Support `--workdir-root` in the `tmt run` command

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [x] extend the test coverage
* [x] include a release note

### CODE REVIEW

**Review by KwisatzHaderach — APPROVED** [review]

**Comment by psss** [comment]
Many tests are failing, it seems that the workdir is not created if it does not exist before. Reproducible easily by removing the `/var/tmp/tmt` directory or setting a different workdir:

    TMT_WORKDIR_ROOT=/tmp/new tmt run discover -v

**Comment by skycastlelily** [comment]
> Many tests are failing, it seems that the workdir is not created if it does not exist before. Reproducible easily by removing the `/var/tmp/tmt` directory or setting a different workdir:
> 
> ```
> TMT_WORKDIR_ROOT=/tmp/new tmt run discover -v
> ```

yes, I was too confident about the mr,  I failed to realize one difference compared to workdir-root-clean mr : workdir-root may not exist for run case:sweat_smile: 

Updated,should be ready now:)

**Review by psss — APPROVED** [review]
Thanks for improving this, looks good!

**Review by thrix — APPROVED** [review]
Works for me, LGTM

**Review by martinhoyer — APPROVED** [review]

**Pull request merged**
