### PR TITLE
Add typing for tmt/steps/report/display.py

### PR DESCRIPTION
**Pull request by janhavlin**
Blocked until #1319 is merged.

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Comment by thrix** [comment]
@psss @lukaszachy seems this is good to go, very short

**Review by optak — APPROVED** [review]
LGTM

**Comment by psss** [comment]
@janhavlin, just a nitpick: Let's start the commit messages with a capital letter as suggested in the [recommendations](https://tmt.readthedocs.io/en/latest/contribute.html#commits) to make them consistent and easy for copy-paste to release notes. Thanks.

**Pull request merged**
