### PR TITLE
Release tmt-1.32.1

### PR DESCRIPTION
**Pull request by martinhoyer**
Fixing spec file version in order to be able to update Fedora packages.

### CODE REVIEW

**Review by psss — APPROVED** [review]

**Comment by happz** [comment]
I've seen the failure else in another PR, glad it's not because of my changes there.

It seems like centos offers pytest 6.2.2 - no idea how this could eve pass :O

**Comment by happz** [comment]
This should help:

```diff
diff --git a/tests/unit/test.sh b/tests/unit/test.sh
index 53864417..6378f207 100755
--- a/tests/unit/test.sh
+++ b/tests/unit/test.sh
@@ -44,7 +44,13 @@ rlJournalStart
             rlRun "TEST_VENV=$(mktemp -d)"
 
             rlRun "python3 -m venv $TEST_VENV --system-site-packages"
-            rlRun "$TEST_VENV/bin/pip install pytest-container pytest-xdist"
+
+            # Only pytest-container <= 0.3.0 works with pytest 6.2.2 in CentOS Stream 9.
+            if rlIsCentOS "=9"; then
+                rlRun "$TEST_VENV/bin/pip install pytest-container==0.3.0 pytest-xdist"
+            else
+                rlRun "$TEST_VENV/bin/pip install pytest-container pytest-xdist"
+            fi
 
             # Note: we're not in the root directory!
             rlRun "$TEST_VENV/bin/python3 -m $PYTEST_COMMAND $PYTEST_PARALLELIZE $PYTEST_MARK ."
```

**Comment by martinhoyer** [comment]
>              rlRun "python3 -m venv $TEST_VENV --system-site-packages"

@happz I think using site-packages will potentially keep producing issues like this going forward. Are you sure you want to keep doing workarounds for version conflicts? 

@psss do you want it fixed as part of this release?

**Comment by happz** [comment]
> > ```
> >          rlRun "python3 -m venv $TEST_VENV --system-site-packages"
> > ```
> 
> @happz I think using site-packages will potentially keep producing issues like this going forward. Are you sure you want to keep doing workarounds for version conflicts?

I'm sure we shouldn't keep such workarounds for too long - I guess it's fine for now, a week or two, or one or two releases, but eventually, it should be resolved.

On the other hand, some of them might be impossible to resolve from our end, like this one. The most recent pytest-container is not compatible with pytest 6.2.2, and CentOS Stream 9 does not ship newer pytest, I'm not sure how we could fix this particular trouble without an exception. Some of them might stick with us :(

**Comment by happz** [comment]
> > pytest-container is not compatible with pytest 6.2.2
> 
> @happz wouldn't it be better to update pytest from pypi rather than lowering plugin versions though? There shouldn't be a conflict, as we're explicitly using venv: `rlRun "$TEST_VENV/bin/python3 -m $PYTEST_COMMAND`.
> 
> something like:
> 
> ```
>              rlRun "python3 -m venv $TEST_VENV --system-site-packages"
>              # pytest-containers 0.4.0 is not compatible with c9s pytest 6.2.2
>              if rlIsCentOS "=9"; then
>                  rlRun "$TEST_VENV/bin/pip install -U pytest"
>              rlRun "$TEST_VENV/bin/pip install pytest-container pytest-xdist"
> ```

Or that, yes. No preference.

**Comment by LecrisUT** [comment]
I am confused, packit should have updated the version automatically on `propose_downstream` what happened here?

**Comment by martinhoyer** [comment]
> I am confused, packit should have updated the version automatically on `propose_downstream` and I don't see any special action in `.packit.yaml` what happened here?

packit is not configured to bump version in .spec file and I wrongly assumed it does so when doing the release commit.

**Comment by LecrisUT** [comment]
But the default should be that it does, on mine it bumps always from `0.0.0`: https://github.com/scikit-build/scikit-build-core/blob/main/.packit.yaml

**Comment by LecrisUT** [comment]
> > But the default should be that it does, on mine it bumps always from `0.0.0`: https://github.com/scikit-build/scikit-build-core/blob/main/.packit.yaml
> 
> yes, tmt is not using default. Same with changelog.

For the `changelog` I saw the [`sync_changelog: true`](https://github.com/teemtee/tmt/blob/1c647fb8b5c8682ffb4a27311487636e9b799d09/.packit.yaml#L5C1-L5C21), but I did not see anything about the version :/. Am I blind or is there something else happening?

**Comment by martinhoyer** [comment]
>     * These both are reporting: "Running default implementation for ActionName.prepare_files"

I'm not yet super familiar with packit to be honest. Perhaps it's done by running get-current-version action, but that's a guess.

**Comment by LecrisUT** [comment]
> > ```
> > * These both are reporting: "Running default implementation for ActionName.prepare_files"
> > ```
> 
> I'm not yet super familiar with packit to be honest. Perhaps it's done by running get-current-version action, but that's a guess.

I have reported upstream. That was my suspicion as well, but I saw that that one was limited to `copr_build` job, in which case it should not have effected that default. This seems like a bug on their side

**Comment by martinhoyer** [comment]
> I have reported upstream. That was my suspicion as well, but I saw that that one was limited to `copr_build` job, in which case it should not have effected that default. This seems like a bug on their side

Not sure about it being a bug, but fwiw packit did detect the old version:
`2024-03-27 15:43:59.022 api.py     WARNING Version '1.31.0' in spec file is outdated.`

**Comment by LecrisUT** [comment]
Indeed, but similarly it did with `scikit-build-core` that I linked there. The weird part where they differ is after the "Running default implementation for ActionName.prepare_files"  line

**Comment by lukaszachy** [comment]
> wouldn't it be better to update pytest from pypi rather than lowering plugin versions though?

+1 I see no point in limiting us to old pytest as long as it doesn't inject newer dependency of tmt itself.

**Comment by LecrisUT** [comment]
Ok, packit came back with an explanation. When using `sync_changelog: true`, this implies version is not bumped. It was not documented as such though, but this explains stuff

**Review by lukaszachy — APPROVED** [review]

**Comment by lukaszachy** [comment]
Infra is not so great today so I'm merging without waiting on it. It is just a few simple lines, what can go wrong. Right? Right?!

**Pull request merged**
