### PR TITLE
Turn `tests.yaml` into a list of tests

### PR DESCRIPTION
**Pull request by happz**
This should allow tests to be repeatable, which is a feature seeked needed in the multi host use cases.

### CODE REVIEW

**Comment by thrix** [comment]
`yq` is not installed, new dependency?

**Review by thrix — APPROVED** [review]
Otherwise LGTM, looks clean to me

**Comment by happz** [comment]
> `yq` is not installed, new test dependency?

Yes, see https://github.com/teemtee/tmt/pull/1854

**Comment by thrix** [comment]
> > `yq` is not installed, new test dependency?
> 
> Yes, see #1854

This is #1854?

**Comment by happz** [comment]
> > > `yq` is not installed, new test dependency?
> > 
> > 
> > Yes, see #1854
> 
> This is #1854?

Dammit! I meant https://github.com/teemtee/tmt/pull/1849

**Comment by happz** [comment]
@psss consider this one for 1.22, it'd push the multi-host support a bit further again

**Review by janhavlin — APPROVED** [review]

**Review by psss — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
