### PR TITLE
Update logger-name for clean

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Comment by skycastlelily** [comment]
Seems like a typo

**Review by happz — APPROVED** [review]

**Review by psss — APPROVED** [review]

**Comment by psss** [comment]
Failing tests were infra problems + avc check on rawhide (irrelevant, needs to be investigated).

**Pull request merged**
