### PR TITLE
Document necessary packages for pip install on Ubuntu

### PR DESCRIPTION
**Pull request by lukaszachy**
Fix: #1952

### CODE REVIEW

**Comment by lukaszachy** [comment]
@happz Ignoring the `provision -h local` use case - Did you run into other problems when using tmt on Ubuntu?

**Comment by happz** [comment]
> @happz Ignoring the `provision -h local` use case - Did you run into other problems when using tmt on Ubuntu?

I'll have my Ubuntu at hand on Saturday, so if you're in no rush, I'd give it a try during weekend.

**Comment by lukaszachy** [comment]
@happz Any luck with Ubuntu and tmt?

**Review by thrix — APPROVED** [review]
LGTM

**Review by psss — APPROVED** [review]
Thanks for documenting this. Looks good. Added just a few minor style adjustments in c881c9ca.

**Pull request merged**
