### PR TITLE
Fix provision for coreos image

### LINKED ISSUE #1569: tmt provision fedora-coreos broke in 1.17
Reproducer: `tmt run finish login provision -h virtual -i fedora-coreos -ddd`

There is nothing usable in log.txt (this is whole file):
```
15:02:30 /var/tmp/tmt/run-003
15:02:30 tmt version: 1.17.0 (255c0918)
15:02:30 Read file '/var/tmp/tmt/run-003/run.yaml'.
15:02:30 Run data not found.
15:02:30 Enabled steps: provision and finish
15:02:30 Create an empty worktree (no metadata tree).
15:02:30 Create the data directory '/var/tmp/tmt/run-003/plans/default/data'.
15:02:30 Found 1 plan.
15:02:30 Write file '/var/tmp/tmt/run-003/run.yaml'.
15:02:30 
15:02:30 /plans/default
15:02:30 info
15:02:30 environment: {'TMT_PLAN_DATA': '/var/tmp/tmt/run-003/plans/default/data'}
15:02:30 context: {}
15:02:30 wake
15:02:30 discover
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/discover/step.yaml'.
15:02:30     Step data not found.
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/discover/tests.yaml'.
15:02:30     Discovered tests not found.
15:02:30     Using the 'DiscoverShell' plugin for the 'shell' method.
15:02:30     status: todo
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/discover/step.yaml'.
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/discover/tests.yaml'.
15:02:30 provision
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/provision/step.yaml'.
15:02:30     Step data not found.
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/provision/guests.yaml'.
15:02:30     Provisioned guests not found.
15:02:30     Using the 'ProvisionTestcloud' plugin for the 'virtual' method.
15:02:30     status: todo
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/provision/step.yaml'.
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/provision/guests.yaml'.
15:02:30 prepare
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/prepare/step.yaml'.
15:02:30     Step data not found.
15:02:30     Using the 'PrepareShell' plugin for the 'shell' method.
15:02:30     status: todo
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/prepare/step.yaml'.
15:02:30 execute
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/execute/step.yaml'.
15:02:30     Step data not found.
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/execute/results.yaml'.
15:02:30     Test results not found.
15:02:30     Using the 'ExecuteInternal' plugin for the 'tmt' method.
15:02:30     status: todo
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/execute/step.yaml'.
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/execute/results.yaml'.
15:02:30 report
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/report/step.yaml'.
15:02:30     Step data not found.
15:02:30     Report step always force mode enabled.
15:02:30     Clean up workdir '/var/tmp/tmt/run-003/plans/default/report'.
15:02:30     status: todo
15:02:30     Using the 'ReportDisplay' plugin for the 'display' method.
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/report/step.yaml'.
15:02:30 finish
15:02:30     Read file '/var/tmp/tmt/run-003/plans/default/finish/step.yaml'.
15:02:30     Step data not found.
15:02:30     Using the 'FinishShell' plugin for the 'shell' method.
15:02:30     status: todo
15:02:30     Write file '/var/tmp/tmt/run-003/plans/default/finish/step.yaml'.
15:02:30 action
15:02:30     Insert a login plugin into the 'finish' step with order '90'.
15:02:30 go
15:02:30     provision
15:02:30     workdir: /var/tmp/tmt/run-003/plans/default/provision
15:02:30         how: virtual
15:02:30         order: 50
15:02:30         user: root
15:02:30         key: []
15:02:30         image: fedora-coreos
15:02:30         memory: 2048 MB
15:02:30         disk: 10 GB
15:02:30         connection: session
15:02:30         arch: x86_64
15:02:31         Guessed image url: 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220918.3.0/x86_64/fedora-coreos-36.20220918.3.0-qemu.x86_64.qcow2.xz'
15:02:31         qcow: fedora-coreos-36.20220918.3.0-qemu.x86_64.qcow2
15:02:31         name: tmt-003-GhoOOxTf
15:02:31     Write file '/var/tmp/tmt/run-003/plans/default/provision/step.yaml'.
15:02:31     Write file '/var/tmp/tmt/run-003/plans/default/provision/guests.yaml'.
15:02:31     finish
15:02:31     workdir: /var/tmp/tmt/run-003/plans/default/finish
15:02:31         login: Starting interactive shell
15:02:31         warn: Failed to push workdir to the guest.
15:02:31         Run 'bash' in interactive mode.
```
Regression in 1.17.0, works for 1.16.0. Affects current 'main' as well.

### PR DESCRIPTION
**Pull request by lukaszachy**
Fix #1569

- [x] write test

### CODE REVIEW

**Comment by lukaszachy** [comment]
@BeeGrech this should make `tmt run provision -h virtual -i fedora-coreos` work again.

**Comment by lukaszachy** [comment]
I've tried to run login and finish separately and it works:

```
$ tmt run --id A pro -h vi -i fedora-coreos
        summary: 1 guest provisioned
$ tmt run --id A  login
        summary: 1 guest provisioned
        login: Starting interactive shell
[root@ibm-p8-kvm-03-guest-02 tree]# 
exit
Shared connection to 127.0.0.1 closed.
        login: Interactive shell finished
$ tmt run --id A  finish
    finish
        guest: stopped
        guest: removed
```

**Comment by BeeGrech** [comment]
+1
looks good

**Review by psss — APPROVED** [review]
Looks good, thanks for fixing this!

**Pull request merged**
