### PR TITLE
Enable the `/tests/discover/libraries` test

### PR DESCRIPTION
**Pull request by psss**
Move the library pruning check to a separate test.
Move the apache check into a separate test as well.
Enable the new tests under `/plans/provision/virtual`.

### CODE REVIEW

**Comment by psss** [comment]
@lukaszachy, we have a success! It worked fine on `fedora`. The test takes about half on hour to finish there. For `centos-stream` we get this:

    Failed to boot testcloud instance (No usable qemu binary exist,
    tried: ['/usr/bin/qemu-system-x86_64', '/usr/libexec/qemu-system-x86_64']).

@frantisekz, are you aware of this?

**Comment by lukaszachy** [comment]
IIRC we had seen that problem already and was solved by installing another package. 

Will try to remember tomorrow.

This is great news.
even if we had to skip nested vm on centos it's much better than nothing.

**Comment by psss** [comment]
> This is great news.

Yes, yes, exactly! 

> even if we had to skip nested vm on centos it's much better than nothing.

And we could (possibly) enable full provision tests for `fedora` only if needed.

**Comment by happz** [comment]
Update: @psss will check this one out, and possibly finish it.

**Review by lukaszachy — APPROVED** [review]
Thanks, this way of making tests for some provision  methods will be very nice.

**Comment by psss** [comment]
All tests green, just the `avc` one catches some irrelevant denials... Will investigate separately.

**Pull request merged**
