### PR TITLE
Type annotations staging

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Comment by lukaszachy** [comment]
tests/full ran in TJ#6934848 (branch pointing to commit ced2570)  and PASS.

**Review by lukaszachy — APPROVED** [review]
All pieces reviewed as they were being merged to this branch.

**Comment by lukaszachy** [comment]
I've added breakage label as some of API changed, however private plugins and wow are updated to be compatible. No known breakage for out-of-tree code exists.

**Review by psss — APPROVED** [review]
This is a bunch of work done, many thanks to all who contributed!

**Pull request merged**
