### PR TITLE
Use sudo where necessary

### PR DESCRIPTION
**Pull request by lukaszachy**
This PR just adds sudo everywhere I could find 'install' + reboot script
IMHO we could use guest method to check+install and for "run as root" to detect if sudo is necessary.

Also tests will be nice. Do we have somewhere documented that password-less sudo is necessary for provision/execute to work correctly?

### CODE REVIEW

**Comment by lukaszachy** [comment]
Lovely, existing tests are green.

@psss - I'm not really sure if I put `self.sudo` initialization at the right place (eg. for 'connect' it is in start() method)

**Comment by lukaszachy** [comment]
I went with 'sudo' as Guest's property initialized first time it is called

**Comment by lukaszachy** [comment]
Cleared milestone, not a priority right now. Maybe next one.

**Comment by lukaszachy** [comment]
And we have more places which require sudo / root  - rsync creates files in `/usr/local/bin`.

**Comment by psss** [comment]
Seems that a solution connected with guest facts and dedicated parameter for methods which need root provileges would be better. Closing, feel free to reopen if you think this approach would be better.

**Pull request closed without merging**
