### PR TITLE
New tests for adjusting `duration` of a test

### PR DESCRIPTION
**Pull request by pellecchialuigi**
Adding 3 new tests for adjust duration:

- Combining multiple duration strings
- Multiplying by a value
- Adding a value

It refers also to #3278

Pull Request Checklist

* [X] extend the test coverage

### CODE REVIEW

**Review by KwisatzHaderach — APPROVED** [review]

**Review by happz — APPROVED** [review]

**Review by psss — APPROVED** [review]
Thanks for improving this!

**Comment by happz** [comment]
Unrelated failures, merging.

**Pull request merged**
