### PR TITLE
Update pre-commit checks

### PR DESCRIPTION
**Pull request by happz**
Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by martinhoyer — APPROVED** [review]
Nice. It would be cool to merge it together with #2666

**Review by psss — APPROVED** [review]
Thanks!

**Comment by happz** [comment]
Yeah, I didn't want to push it into 1.32, I felt it's pretty late, and no actual bug was reported by new linters. But if you feel it's fine, sure, the sooner the better.

**Comment by martinhoyer** [comment]
> Yeah, I didn't want to push it into 1.32, I felt it's pretty late, and no actual bug was reported by new linters. But if you feel it's fine, sure, the sooner the better.

I was also waiting for 1.32 to be out to update the linters :)
There are interesting new ruff rules and I've been playing with [refurb](https://github.com/dosisod/refurb), which is pretty impressive. Good to have this commit in before checking them out here.

**Comment by psss** [comment]
Ok, let's rather merge soon.

**Pull request merged**
