### PR TITLE
Execute script should not be used with discover

### PR DESCRIPTION
**Pull request by psss**
Combining `script` under the `execute` step with tests explored
under the `discover` step might be confusing as it's not clear
which of them should be run first and in general it does not make
much sense to define tests at two places. Update docs as well.

### CODE REVIEW

**Comment by psss** [comment]
Good point, @lukaszachy! Docs updated.

**Comment by pemensik** [comment]
Maybe it could be mentioned that discover: has no default. If it is omitted, it means neither shell or fmf would be used. I did not know there is implicit ``discover: how: none``, which seems to be the default. But cannot be specified manually.

**Comment by psss** [comment]
Hm, the `discover` step default method is `shell`, it should not be `None`. Step defaults are documented here:

 * https://tmt.readthedocs.io/en/latest/spec/plans.html

What led you to the `None` value?

**Comment by pemensik** [comment]
Okay, shell without ``tests:`` does nothing. Okay, makes sense. Just guessed no action is equivalent to None. But shell with empty tests does the same thing, nothing.

**Pull request merged**
