### PR TITLE
Extract `tmt try` and `tmt init` into their own `tmt.cli` modules

### PR DESCRIPTION
**Pull request by happz**
Ongoing process of splitting `tmt.cli`.

Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Comment by psss** [comment]
`/tests/unit/with-system-packages/basic` is failing, looks like some further adjustments are needed:

    AttributeError: module 'tmt.cli._root' has no attribute '_construct_trying_provision_options'

**Review by thrix — APPROVED** [review]
LGTM, just moving code around, I did not find any changes

**Review by KwisatzHaderach — APPROVED** [review]

**Review by psss — APPROVED** [review]

**Comment by psss** [comment]
One last change needed, fixed in 4b0eb32b, ready for merge.

**Comment by psss** [comment]
The `provision` job failures are irrelevant, merging.

**Pull request merged**
