### PR TITLE
Just make options passing possible in more generic way.

### PR DESCRIPTION
**Pull request by RHEmployee**
Building block (not only) for ssh options.

This is work in progress.

### CODE REVIEW

**Comment by psss** [comment]
This is a very brief draft indeed. @RHEmployee, are you going to work on this?

**Comment by RHEmployee** [comment]
> This is a very brief draft indeed. @RHEmployee, are you going to work on this?

I would like to work on this but some help will be needed.

**Comment by RHEmployee** [comment]
Hi. Seems to be easier to implement in:
https://github.com/teemtee/tmt/pull/1088
in the end.

Closing soon or later.

**Comment by psss** [comment]
Seems to be already covered by #1673.

**Pull request closed without merging**
