### PR TITLE
Simplify reportportal plugin test using yq

### PR DESCRIPTION
**Pull request by 4N0body5**
PR for #2183 [WIP]

### CODE REVIEW

**Comment by 4N0body5** [comment]
There is a struggle with yq working on key starting with a symbol, particularly the `/` in this case.
I found out it has different behaviour in testing environment (`mkvirtualenv tmt`) and outside of it, see the example below.
Screenshot from 2023-07-05 18-23-43

The question is what behaviour will be applied once the PR is merged. As it currently fails in testing environment.
And how to make it work?

**Comment by idorax** [comment]
> The question is what behaviour will be applied once the PR is merged. As it currently fails in testing environment.
> And how to make it work?

Hi @4N0body5, how about removing char `/` when using `yq`? For example, 

```bash
(tmt) huanli@KVM:reportportal$ cat data/test.fmf | head -4
/bad:
    summary: Failing test
    contact: tester@redhat.com
    test: echo "Something bad happened!"; false
(tmt) huanli@KVM:reportportal$ cat data/test.fmf | sed 's%^/%%g' | head -4
bad:
    summary: Failing test
    contact: tester@redhat.com
    test: echo "Something bad happened!"; false
(tmt) huanli@KVM:reportportal$ 
(tmt) huanli@KVM:reportportal$ cat data/test.fmf | sed 's%^/%%g' | yq -r '.bad'
{
  "summary": "Failing test",
  "contact": "tester@redhat.com",
  "test": "echo \"Something bad happened!\"; false"
}
(tmt) huanli@KVM:reportportal$ 
(tmt) huanli@KVM:reportportal$ cat data/test.fmf | sed 's%^/%%g' | yq -r '.bad.summary'
Failing test
```

**Comment by happz** [comment]
Can you try wrapping key in your filter with double quotes, https://github.com/jqlang/jq/issues/38#issuecomment-9770240 ? jq/yq should be fully capable with keys with spaces, dashes and other symbols too.

**Comment by 4N0body5** [comment]
> Can you try wrapping key in your filter with double quotes, [jqlang/jq#38 (comment)](https://github.com/jqlang/jq/issues/38#issuecomment-9770240) ? jq/yq should be fully capable with keys with spaces, dashes and other symbols too.

@happz I tried all the ways to wrap the key with symbol (single, quotes, double quotes, escaping, etc.). They all work unless I try it in the testing environment. And I don't really know what it means.

**Comment by 4N0body5** [comment]
@psss @happz Thank you very much for your answers..

> Can you try wrapping key in your filter with double quotes, [jqlang/jq#38 (comment)](https://github.com/jqlang/jq/issues/38#issuecomment-9770240) ? jq/yq should be fully capable with keys with spaces, dashes and other symbols too.

Sorry for ignorance, I overseen the need of double quotes inside of the quotes.


> Do you see the problem even if the test name is inside double quotes like in the example above?

You're right, it does work now in both environments! This must be truly the only combination I haven't tried and does work. Unfortunately for me, because this way I cannot use variables there because of the single quotes.

Now I'm simplifying the test, I wanted to omit the analogous sections and awful functions per each test and replace it with neat function. But it requires the use of variables as a key for yq.
The question is if it's worth it rewrite it completely, or all what is wanted is to replace greps for yq..?

Example:
image

**Comment by psss** [comment]
Try something like this:

    rlRun "yq -r '.\"/test/$variable\"'"

This should expand the variable just fine.

**Comment by 4N0body5** [comment]
Please review...
There are two commits, the first one simplifying only (extracting fmf data with yq), the other one with complete redesign (for generalization and easier maintenance), but it seems to be just more complicated now.
Please let me know your opinions.

**Review by psss — APPROVED** [review]
Thanks for improving this! Looks good. Squashed and rebased on the latest `main`.

**Pull request merged**
