### PR TITLE
Release 1.36.0

### PR DESCRIPTION
**Pull request by martinhoyer**

### CODE REVIEW

**Review by psss — APPROVED** [review]
Looks good. Not many news in the release notes this time, right? I quickly skimmed through the commits and the only thing which might be worth mentioning are the preparations for the subresult support:

32a35b66 Show the subresults and their checks in the HTML report (#3095)
c27aef51 Show subresults and their checks in report display plugin (#3107)
efa026f7 Rename result phase to subresult

But not sure, probably not worth it when it does not bring anything tangible to the user?

**Comment by martinhoyer** [comment]
> Looks good. Not many news in the release notes this time, right? I quickly skimmed through the commits and the only thing which might be worth mentioning are the preparations for the subresult support:
> 
> [32a35b6](https://github.com/teemtee/tmt/commit/32a35b66f6e89f031773f8adc1b1a5d349fbf718) Show the subresults and their checks in the HTML report (#3095) [c27aef5](https://github.com/teemtee/tmt/commit/c27aef51a6d73fc3079ce15f52086dfe2b3b5598) Show subresults and their checks in report display plugin (#3107) [efa026f](https://github.com/teemtee/tmt/commit/efa026f7169195898b25d1fa0af42a5c0628c049) Rename result phase to subresult
> 
> But not sure, probably not worth it when it does not bring anything tangible to the user?

I'm also not sure what's the policy for release notes. My idea is to improve the github release notes and have the rtd release section for items that could do with longer text.  
But that's in future, here I think it wouldn't hurt to add a note about the subresults? :)

**Comment by psss** [comment]
> But that's in future, here I think it wouldn't hurt to add a note about the subresults? :)

Feel free to add it or forget about my comment, both is fine from my point of view :)

**Comment by psss** [comment]
Yeah, looks great! 👍

**Pull request merged**
