### PR TITLE
[WIP] initial: jats discovery plugin

### PR DESCRIPTION
**Pull request by fernflower**
Is capable of running jats-tests in leapp repository with

tmt run -a provision  -h connect -g 10.0.78.255 plans --name "integration-leapp-repository"

### CODE REVIEW

**Comment by thrix** [comment]
nah, such a stupid error :(

**Comment by psss** [comment]
Hi, is there a plan to finish this? Or has the idea been abandoned?

**Comment by fernflower** [comment]
Hi! Yes, the idea is not abandoned. 
Or would you rather close it now and reopen when oamg team finally finds time for it?

**Comment by psss** [comment]
Ok, thanks for the update. I was just not sure, if this is still valid.

**Comment by fernflower** [comment]
We decided to abandon the idea of running jats tests with tmt. Instead we will port select jats tests to our new integration test framework where native tmt feature work for us already.

**Pull request closed without merging**
