### PR TITLE
Remove duplicated keys when showing plugin details

### PR DESCRIPTION
**Pull request by idorax**
fix: #1343

### CODE REVIEW

**Comment by lukaszachy** [comment]
Thanks @idorax. While it fixes this and future issue I'm not sure if we should allow duplicate keys at all. I can't think of use case when it is desired to have them listed at two (or more) places. @psss?

**Comment by psss** [comment]
Agree with @lukaszachy. I'd also say that the same key should not be present multiple times in the key lists. Also, I guess `list(set(...))` could possibly change the order? Would be good to keep the original order.

**Review by lukaszachy — CHANGES_REQUESTED** [review]
Please fix by removing the duplicate instead.

**Comment by idorax** [comment]
> Please fix by removing the duplicate instead.

Hi @psss and @lukaszachy, I have updated the related code to remove the duplicated keys and keep the original order. Please help to review,  thanks!

**Comment by idorax** [comment]
> @idorax Sorry, I meant to find in discover plugins code where I've added 'dist-git-source' second time and remove it from there. And check for other possible duplicates.

Hi @lukaszachy, `dist-git-source` and `dist-git-type` are removed from `_keys` in class `DiscoverFmf`, please help to review again, thanks!

**Review by lukaszachy — APPROVED** [review]
Thank you, LGTM.

**Pull request merged**
