### PR TITLE
Add typing for multihost.py

### PR DESCRIPTION
**Pull request by guy9050**

### CODE REVIEW

**Comment by happz** [comment]
@guy9050 please, update also `mypy.ini` and add the file to the list of files protected by mypy.

I'd also recommend installing pre-commit in your repository, it should catch some of the issues before submitting your changes.

**Comment by guy9050** [comment]
> @guy9050 please, update also `mypy.ini` and add the file to the list of files protected by mypy.
> 
> I'd also recommend installing pre-commit in your repository, it should catch some of the issues before submitting your changes.

Thanks, also updated mypy.ini in my other PR's.
About pre-commit - thanks. fixed. it's installed but for some reason it doesn't run automatically during commit. I'm looking into it

**Comment by guy9050** [comment]
Pre-commit is hitting "tmt/steps/prepare/multihost.py:6: error: Class cannot subclass "PreparePlugin" (has type "Any")"
not sure how it's best to deal with it

**Comment by happz** [comment]
> Pre-commit is hitting `"tmt/steps/prepare/multihost.py:6: error: Class cannot subclass "PreparePlugin" (has type "Any")"` not sure how it's best to deal with it

That is expected, since mypy is not allowed to peek into imported files, therefore it must assign `Any` to `PreparePlugin`. We cannot let mypy to peek into other files, yet, so until that happens, I'd recommend this: https://github.com/teemtee/tmt/blob/main/tmt/steps/provision/artemis.py#L272 - a TODO comment + `type: ignore[misc]`, that should silence mypy.

**Review by happz — APPROVED** [review]

**Review by psss — APPROVED** [review]
Looks good.

**Pull request merged**
