### PR TITLE
Push using `sudo rsync` when necessary

### PR DESCRIPTION
**Pull request by lukaszachy**
Necessary when provision connects as non-root as
tmt needs to create tmt-* scripts in /usr/local/bin

Asking for preliminary feedback

PR Checklist:
* [x] implement the feature
* [x] extend the test coverage

### CODE REVIEW

**Comment by lukaszachy** [comment]
Reproducer: ` tmt run -a provision -h virtual -i fedora-coreos -u core execute -h tmt  --script echo`

Current version:
```
    execute
        how: tmt
        fail: Failed to push workdir to the guest. This usually means that login as 'core' to the guest does not work.
    finish
        guest: stopped
        guest: removed
        summary: 0 tasks completed

stderr (2/2 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rsync: [receiver] mkstemp "/usr/local/bin/.tmt-abort.rmUXar" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1336) [sender=3.2.7]

Failed to run command: None Reason: Command returned '23'.
```

**Comment by lukaszachy** [comment]
Note that the `-u core` will not be necessary once #1895 is merged

**Review by happz — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Pull request merged**
