### PR TITLE
Finish unit testing of HW transformations in mrack plugin

### PR DESCRIPTION
**Pull request by happz**
Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Review by psss — APPROVED** [review]

**Comment by psss** [comment]
Full provision test [failed](http://artifacts.osci.redhat.com/testing-farm/cdf65df8-2700-43a5-8d6b-4777e48197c0/) on known issues only:

* #2687 
* #2744 

Otherwise green.

**Pull request merged**
