### PR TITLE
Support `cpu.model-name` hardware requirement for mrack

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [x] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Review by happz — APPROVED** [review]

**Review by therazix — APPROVED** [review]

**Comment by happz** [comment]
@skycastlelily please, resolve the conflict & rebase on top of `main`.

**Comment by skycastlelily** [comment]
Updated^^

**Pull request merged**
