### PR TITLE
Support to lint attribute 'id'

### PR DESCRIPTION
**Pull request by idorax**
fix: #1367

### CODE REVIEW

**Comment by lukaszachy** [comment]
@idorax Will you have time to look into this today/tomorrow? I'd love to get this fixed in 1.16 which is close. If you are busy / other priorites no problem, I'll create PR.

**Comment by idorax** [comment]
> @idorax Will you have time to look into this today/tomorrow? I'd love to get this fixed in 1.16 which is close. If you are busy / other priorites no problem, I'll create PR.

Sure, I'm working on it, will ask your review today.

**Review by lukaszachy — CHANGES_REQUESTED** [review]
Nice, works well. Please add tests, there are 
/tests/plan/lint
/tests/story/lint
/tests/test/lint

I'd say add 'id' to one of 'good' examples each of this tests uses (for example /tests/plan/lint has 
tests/plan/lint/data/good.fmf so `cd tests/plan/lint/data && tmt plans id /good`)

Similar for one of test files (e.g. tests/test/lint/data/good.fmf)

And I've found out 'story' has same problem - so add test first please (eg. tests/story/lint/data/good.fmf) and fix it please.

Once you have it do not hesitate and squash everything so it can be merged.

**Comment by idorax** [comment]
> And I've found out 'story' has same problem - so add test first please (eg. tests/story/lint/data/good.fmf) and fix it please.

The tests for `story` is updated, but `tmt story lint` is not fixed, please wait for a while ...

**Comment by idorax** [comment]
> > And I've found out 'story' has same problem - so add test first please (eg. tests/story/lint/data/good.fmf) and fix it please.
> 
> The tests for `story` is updated, but `tmt story lint` is not fixed, please wait for a while ...

The fix for `tmt story lint` is ready by introducing `EXTRA_STORY_KEYS = ("id".split())`.

**Review by lukaszachy — APPROVED** [review]
LGTM, thank you. I'll squash and merge soonish.

**Comment by idorax** [comment]
> LGTM, thank you. I'll squash and merge soonish.

Thanks! The four commits have been squashed, please help to update the comment if it is not exactly proper, thanks!

**Pull request merged**
