### PR TITLE
Support `tpm.version` hardware requirement for `mrack`

### PR DESCRIPTION
**Pull request by skycastlelily**
Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [x] extend the test coverage
* [x] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

### CODE REVIEW

**Comment by happz** [comment]
@skycastlelily rebase, please, when you have a moment.

**Comment by skycastlelily** [comment]
Updated^^

**Review by happz — APPROVED** [review]

**Review by therazix — APPROVED** [review]

**Review by KwisatzHaderach — APPROVED** [review]

**Comment by happz** [comment]
Unrelated failures, merging.

**Pull request merged**
