### PR TITLE
Capture exceptions when getting image_url

### PR DESCRIPTION
**Pull request by idorax**
fixes: #1657

### CODE REVIEW

**Comment by idorax** [comment]
Hi @psss, @lukaszachy and @frantisekz, please help to review the patch which is pretty straightforward, thanks!

**Comment by frantisekz** [comment]
LGTM, there is probably no harm in doing this :)

I am trying, from testcloud side, to return None in cases when something fails, but the url fetching is often, by definition, fragile.

**Review by ZelenyMartin — APPROVED** [review]
LGTM

**Comment by idorax** [comment]
The failures of `testing-farm:centos-stream-9-x86_64` are because of:
```
# https://artifacts.dev.testing-farm.io/36b68492-22cf-4bf0-a535-8bbf23387ae0/
... <snip> ...

Failed to run command: podman exec tmt-001-puTndVVJ bash -c 'export TMT_PLAN_DATA=/var/tmp/tmt/run-001/plans/data; uname -r' Reason: Command returned '255'.

stderr (1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: can only create exec sessions on running containers: container state improper
```
@ZelenyMartin and @lukaszachy, any idea or suggestion?

**Review by psss — APPROVED** [review]
Looks ok, thanks.

**Comment by psss** [comment]
> Error: can only create exec sessions on running containers: container state improper

Yes, this error appears across all pull requests. Seems to be a `podman` related issue on `c9s`.

@thrix, have you seen this? Is there anything new/different in the `c9s` environment? Tried to reproduce with the latest `CentOS-Stream-9` image with no luck. Everything seems to be working just fine.

**Pull request merged**
