### PR TITLE
Change help text of the `tmt --root` option

### PR DESCRIPTION
**Pull request by ivet1987**
Change help text of '-r' option. 
The original text was a bit confusing according to issue https://github.com/teemtee/tmt/issues/371
If you have another suggestion, let me know.

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Review by happz — APPROVED** [review]

**Review by psss — APPROVED** [review]
Thanks for fixing this, @ivet1987. And welcome to the `tmt` contributors! :)

**Comment by psss** [comment]
I've just updated the commit message to match our [recommendations](https://tmt.readthedocs.io/en/latest/contribute.html#commits).

**Comment by ivet1987** [comment]
> I've just updated the commit message to match our [recommendations](https://tmt.readthedocs.io/en/latest/contribute.html#commits).

@psss  Thanks, still learning :-)

**Pull request merged**
