### PR TITLE
Fix default `framework`, remove old execution methods

### PR DESCRIPTION
**Pull request by psss**
Set the default test `framework` value to `shell`. Remove support
for deprecated execution methods as the special handling of them
is not compatible with the default value for the `framework` key.
Clean up this obsoleted part and adjust related test coverage.

### CODE REVIEW

**Comment by psss** [comment]
@happz, two minor fixes I ran into during the normalization debug output review.

**Review by happz — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Comment by lukaszachy** [comment]
Internal-wow test will be fixed in MR 273, I'll reschedule once merged

**Comment by psss** [comment]
> Internal-wow test will be fixed in MR 273, I'll reschedule once merged

Thanks, @lukaszachy!

**Comment by psss** [comment]
So... after closer investigation of the failed tests I realized that the `framework: shell` default does not work with the old hacks which enable the ancient `beakelib.tmt` and `shell.tmt` execution methods. Thus I'm proposing to get rid of them in cb2f750. Originally the timing proposed for deprecation was `March 2021`, later proposed for `2.0`. I think the warning was there long enough and we should go bravely forward.

Probably not a good candidate to be merged as one of the last pull requests just before the release though... Let's move to `1.18` instead?

**Comment by happz** [comment]
Could you check what I did in https://github.com/teemtee/tmt/pull/1461/files#diff-458194650925d6c3ea27ee8a599db67a78a23dbb0b353cddc9e2b8387b54d993R397. It’s touching this area as well - would my changes affect the issue or reproducer? Any chance to amend these two changes?

I’m hoping for the less painful rebase of my large patch :/

**Comment by psss** [comment]
> I’m hoping for the less painful rebase of my large patch :/

As discussed and agreed on the chat, let's rather move this to `1.18` so it will be merged only after your changes.

**Comment by psss** [comment]
> So... after closer investigation of the failed tests I realized that the `framework: shell` default does not work with the old hacks which enable the ancient `beakelib.tmt` and `shell.tmt` execution methods. Thus I'm proposing to get rid of them in [cb2f750](https://github.com/teemtee/tmt/commit/cb2f750be678056714ad7960d2f729231c78ef8c). Originally the timing proposed for deprecation was `March 2021`, later proposed for `2.0`. I think the warning was there long enough and we should go bravely forward.

Any general thoughts on this? @lukaszachy, @thrix, @FrNecas, @happz, do you agree with the proposed cleanup in `1.18`?

**Comment by happz** [comment]
> > So... after closer investigation of the failed tests I realized that the `framework: shell` default does not work with the old hacks which enable the ancient `beakelib.tmt` and `shell.tmt` execution methods. Thus I'm proposing to get rid of them in [cb2f750](https://github.com/teemtee/tmt/commit/cb2f750be678056714ad7960d2f729231c78ef8c). Originally the timing proposed for deprecation was `March 2021`, later proposed for `2.0`. I think the warning was there long enough and we should go bravely forward.
> 
> Any general thoughts on this? @lukaszachy, @thrix, @FrNecas, @happz, do you agree with the proposed cleanup in `1.18`?

Perfectly fine with me.

**Comment by lukaszachy** [comment]
OK to clean the code.

**Comment by thrix** [comment]
@psss fine with me also, let's make sure we mention this in release notes

**Pull request merged**
