### PR TITLE
Enable variable expansion for dynamic references

### PR DESCRIPTION
**Pull request by kkaarreell**
Adds possibility to use variables inside the `.tmt/ref.fmf` file.

### CODE REVIEW

**Comment by kkaarreell** [comment]
The first 6 commits come from https://github.com/teemtee/tmt/pull/1590 and will be removed later.

**Comment by kkaarreell** [comment]
@psss Hi, is commit c95aab9bfa9e980c51bbed1e21d58e8ad492ca40 using the right approach?

**Review by psss — APPROVED** [review]
Thanks, looks good. I've just added a short example to the documentation.

**Comment by psss** [comment]
Merged. Feel free to open future pull requests from branches directly in the `tmt` repository.

**Pull request merged**
