### PR TITLE
Add favicon to tmt docs

### PR DESCRIPTION
**Pull request by happz**
Pull Request Checklist

* [x] implement the feature

### CODE REVIEW

**Review by therazix — APPROVED** [review]

**Comment by happz** [comment]
> Nice! Thanks for the improvement. Thinking a bit about the icon size: Currently the image is 700x700 and the size is 432K, so the icon is larger then the page content :) But it will be cached, I guess, so probably not worth it?

It will be cached for sure, and we definitely can create a smaller one :)

**Comment by psss** [comment]
Ok :) Adding here: https://github.com/teemtee/docs/pull/5

**Comment by martinhoyer** [comment]
Screenshot from 2024-07-02 14-51-40
See the .ico from https://github.com/teemtee/tmt/pull/3072 (on the left) vs tmt.readthedocs.io/en/latest/

**Comment by happz** [comment]
@martinhoyer Yeah, I didn't bother, I wouldn't even notice the image looks a bit weird on my screen. I guess it's like the sound quality, at some point my human ear don't hear the difference :)

**Comment by martinhoyer** [comment]
> @martinhoyer Yeah, I didn't bother, I wouldn't even notice the image looks a bit weird on my screen. I guess it's like the sound quality, at some point my human ear don't hear the difference :)

/me hiding his audio equipment :eyes:

**Pull request merged**
