### PR TITLE
Do not use `mypy` cache for `ruamel.yaml`

### PR DESCRIPTION
**Pull request by martinhoyer**
Trying to fix the annoying mypy fails every second run. Tested locally by running `pre-commit run --all-files` repeatably.

See https://github.com/python/mypy/issues/12664#issuecomment-2518393807

### CODE REVIEW

**Comment by martinhoyer** [comment]
Things got a bit messy when another module override was added to the mypy config in pyproject.toml. Adding back the`mypy.ini` file. Any better ideas?

**Comment by happz** [comment]
> Things got a bit messy when another module override was added to the mypy config in pyproject.toml. Adding back the`mypy.ini` file. Any better ideas?

How does `pyproject.toml` looks like with the change? I’m not a big fan of fracturing the configuration into smaller files, maybe the price wouldn’t be that high.

**Comment by martinhoyer** [comment]
> > Things got a bit messy when another module override was added to the mypy config in pyproject.toml. Adding back the`mypy.ini` file. Any better ideas?
> 
> How does `pyproject.toml` looks like with the change? I’m not a big fan of fracturing the configuration into smaller files, maybe the price wouldn’t be that high.

I actually don't know how working pyproject.toml would look like, as I didn't manage to get it working. 
Based on [docs](https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml), it should just be adding 
```
[[tool.mypy.overrides]]
module = "ruamel.*"
cache_dir = "/dev/null"
```
under the existing overrides section, but that breaks things.

**Comment by martinhoyer** [comment]
> args: [--config-file=pyproject.toml]

This is redundant as mypy looks there if mypy.ini or .mypy.ini is not present. Was there any explicit reason for it in the first place?

**Review by psss — APPROVED** [review]
Nice! Thanks much for getting rid of this!

**Pull request merged**
