### PR TITLE
Fixes Artemis guest data class link

### PR DESCRIPTION
**Pull request by happz**

### CODE REVIEW

**Review by thrix — APPROVED** [review]
LGTM

**Review by lukaszachy — APPROVED** [review]

**Comment by TomasTomecek** [comment]
Nice, Fedora 37 builds and tests are working just fine :)

**Comment by thrix** [comment]
rebased, I would add this to `type-annotations-staging` mix

**Comment by thrix** [comment]
@happz I will try to rebase this

**Comment by thrix** [comment]
F35 failure is expected

**Pull request merged**
